/**
 * Blog SEO — Le Congo D'Abord
 *
 * Each article targets specific DRC political search keywords and contains
 * dense internal links (dynamic hyperlinks) to platform pages, plus
 * cross-links between related articles. Content blocks support inline
 * links via the {text|href} token syntax rendered by the blog pages.
 */

export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  keywords: string[];
  date: string;
  author: string;
  category: string;
  readMinutes: number;
  related: string[]; // slugs — dynamic cross-linking between articles
  content: string[]; // paragraphs; {text|/path} tokens become hyperlinks
  lang?: 'fr' | 'ln' | 'sw'; // language code (defaults to fr) for hreflang/JSON-LD
  faq?: { q: string; a: string }[]; // powers the FAQ section + FAQPage schema (AI answers, rich results)
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: 'parti-politique-ia-rdc',
    title: "Parti politique IA en RDC : comment ça fonctionne",
    description:
      "Le Congo D'Abord est le premier parti politique congolais propulsé par l'IA : sélection au mérite, transparence totale et 23 agents au travail 24h/24.",
    keywords: ['parti politique RDC', 'intelligence artificielle Congo', 'politique congolaise', 'Congo D\'Abord', 'IA Afrique'],
    date: '2026-08-01',
    author: 'Le Congo D\'Abord',
    category: 'Innovation',
    readMinutes: 6,
    related: ['selection-candidats-merite', 'transparence-cotisations', 'snto-promesses-projets'],
    content: [
      "La République Démocratique du Congo entre dans une nouvelle ère politique. {Le Congo D'Abord|/} est le premier parti politique congolais dirigé par des citoyens et renforcé par l'intelligence artificielle — pas comme un slogan de campagne, mais comme une infrastructure réelle qui fonctionne aujourd'hui, ouverte et vérifiable par tous.",
      "Pendant des décennies, la politique congolaise a fonctionné à l'envers : l'argent achetait les candidatures, la tribu décidait des postes, et les promesses s'évaporaient une fois le pouvoir atteint. Un parti bâti autour de l'IA renverse cette logique parce que la machine applique la même règle à tout le monde, sans favoritisme ni passe-droit.",
      "Concrètement, {23 agents IA spécialisés|/projects} travaillent pour le parti 24 heures sur 24 : validation des {inscriptions de membres|/register}, cartographie des adhérents dans les 26 provinces, {analyse des profils et sélection des candidats|/candidates}, génération de {politiques publiques|/policy}, priorisation des {besoins d'infrastructure|/infrastructure} signalés par les citoyens, et suivi des projets nationaux via le {système SNTO|/projects}.",
      "Le principe fondamental ne change jamais : l'IA propose, les humains décident. Aucune décision finale n'est prise par une machine. L'intelligence artificielle élimine le favoritisme et l'arbitraire, mais les organes élus du parti gardent seuls le pouvoir de décision — la technologie est un garde-fou anti-corruption, pas un dirigeant.",
      "Chaque membre est enregistré dans une structure à 7 niveaux, du village jusqu'à la présidence, en passant par les territoires, communes et quartiers. Où que vous viviez, vous avez une place et une voix. La diaspora congolaise d'Afrique, d'Europe, des Amériques et d'Asie est pleinement intégrée. Consultez le {tableau de bord national|/dashboard} pour voir la structure en action.",
      "La confiance se mérite. C'est pourquoi chaque cotisation entre dans un {registre public|/contributions} — pas de caisse noire — et pourquoi les données sensibles des membres sont protégées par un chiffrement AES-256 de niveau bancaire. Vous pouvez vérifier nos engagements sur la page {comment nous tenons nos promesses|/promesses}.",
      "L'adhésion est entièrement gratuite. Vous ne cotisez — un dollar par mois — que lorsque vous le décidez, et vous voyez exactement où va cet argent. C'est ainsi qu'un parti redevient la propriété de ses membres plutôt que de ses financiers.",
      "Rejoignez le mouvement dès aujourd'hui : {inscrivez-vous en 6 étapes simples|/register} et devenez acteur de la transformation nationale du Congo.",
    ],
    faq: [
      { q: "Est-ce une intelligence artificielle qui dirige le parti ?", a: "Non. L'IA analyse, propose et rend le favoritisme impossible, mais toutes les décisions finales appartiennent aux organes élus du parti. La règle est simple : l'IA propose, les humains décident." },
      { q: "Combien coûte l'adhésion au Congo D'Abord ?", a: "L'adhésion est gratuite. La cotisation est volontaire : 1 USD par mois ou 12 USD par an, payable par mobile money, et chaque franc est suivi dans un registre public." },
      { q: "Comment l'IA empêche-t-elle la corruption ?", a: "Les candidats sont classés par une formule de mérite publique et identique pour tous, et les cotisations sont tracées publiquement. Ni l'argent, ni la tribu, ni le piston ne peuvent modifier un score ou dissimuler un flux financier." },
    ],
  },
  {
    slug: 'selection-candidats-merite',
    title: 'Comment nos candidats sont choisis au mérite en RDC',
    description:
      "Au Congo D'Abord, les candidats se méritent : une formule publique à 8 critères (éducation, intégrité, ancrage local) que ni l'argent ni le piston ne truquent.",
    keywords: ['candidats élections RDC', 'méritocratie Congo', 'sélection candidats', 'élections 2028 RDC', 'scoring politique'],
    date: '2026-08-01',
    author: 'Le Congo D\'Abord',
    category: 'Transparence',
    readMinutes: 5,
    related: ['parti-politique-ia-rdc', 'academie-politique-formation', 'transparence-cotisations'],
    content: [
      "Dans la politique congolaise traditionnelle, les candidatures s'achètent. Au {Congo D'Abord|/}, elles se méritent. Notre {système de sélection des candidats|/candidates} repose sur une formule publique à 8 critères que personne — pas même le fondateur — ne peut contourner.",
      "Pourquoi une formule plutôt qu'une décision de couloir ? Parce qu'une règle écrite, publique et appliquée par la machine à tous les profils de la même manière retire aux réseaux d'influence leur pouvoir de placer un cousin ou un bailleur. Le mérite devient vérifiable, et donc défendable devant les électeurs.",
      "La formule : Éducation (15%) + Expérience professionnelle (20%) + Crédibilité locale (15%) + Leadership (15%) + Statut de cotisation (10%) + {Formation complétée|/training} (10%) + Score d'intégrité (10%) + Capacité linguistique (5%). Total : 100 points, affichés publiquement pour chaque candidat.",
      "Pour chaque poste — du chef de cellule au candidat député — l'intelligence artificielle analyse tous les profils éligibles et propose les trois meilleurs, avec scores détaillés et justifications. Les organes élus du parti choisissent ensuite parmi ces trois. C'est la fin des parachutages et des candidatures achetées.",
      "Une règle est inviolable : sans {cotisation à jour|/contributions}, aucune éligibilité. Un dollar par mois — la cotisation la plus accessible du pays — garantit que le parti appartient à ses membres cotisants, pas à des financiers de l'ombre. Découvrez pourquoi ce {choix de financement change tout|/promesses}.",
      "Le score n'est pas une fatalité : il se construit. Chaque membre peut l'améliorer en suivant les {14 modules de l'Académie Politique|/training} — leadership, gouvernance locale, finances publiques, éthique — ou en renforçant son ancrage de terrain dans sa {province|/province}. Votre avenir politique dépend de votre travail, pas de vos connexions.",
      "Ce système protège aussi les électeurs : en votant pour un candidat du parti, un citoyen sait que cette personne a franchi une barre de compétence et d'intégrité mesurée, et non acheté sa place. C'est une garantie rare dans la région.",
      "Vérifiez votre éligibilité : {créez votre profil gratuit|/register} et découvrez votre score, puis suivez la formation pour l'améliorer.",
    ],
    faq: [
      { q: "Qui décide finalement des candidats ?", a: "L'IA classe les profils selon la formule publique et propose les trois meilleurs par poste, mais le choix final revient toujours aux organes élus du parti. La machine objective, l'humain tranche." },
      { q: "Peut-on améliorer son score de candidat ?", a: "Oui. Le score évolue avec la formation de l'Académie Politique, l'expérience, l'ancrage local et une cotisation à jour. Il récompense le travail réel, pas les relations." },
      { q: "Faut-il être diplômé pour être candidat ?", a: "L'éducation ne compte que pour 15 %. L'expérience, le leadership, la crédibilité locale et l'intégrité pèsent davantage : un profil de terrain solide peut obtenir un excellent score." },
    ],
  },
  {
    slug: 'transparence-cotisations',
    title: 'La cotisation à 1 USD qui change la politique en RDC',
    description:
      "La cotisation de 1 USD/mois du Congo D'Abord : traçable publiquement, sans financier occulte, pour un parti qui appartient réellement à ses membres.",
    keywords: ['cotisation parti politique', 'financement politique RDC', 'transparence Congo', 'mobile money RDC', 'adhésion parti'],
    date: '2026-08-02',
    author: 'Le Congo D\'Abord',
    category: 'Transparence',
    readMinutes: 4,
    related: ['selection-candidats-merite', 'parti-politique-ia-rdc', 'un-dollar-pouvoir-mobile-money'],
    content: [
      "Qui finance un parti le contrôle. C'est la règle non écrite de la politique dans toute la région, et c'est la raison pour laquelle tant de promesses meurent après les élections. {Le Congo D'Abord|/} a fait le choix inverse : le parti est financé par ses membres, à raison d'un dollar par mois — ou 12 dollars par an, la formule recommandée.",
      "L'adhésion, elle, est entièrement gratuite. On ne paie pas pour entrer ; on cotise, quand on le décide, pour financer un mouvement qu'on contrôle. Cette distinction change tout : le pouvoir reste du côté des membres, pas des bailleurs.",
      "Chaque paiement passe par mobile money (M-Pesa, Orange Money, Airtel Money) et est enregistré dans le {registre public des cotisations|/contributions}. Chaque membre voit son statut ; chaque total est visible par tous. La transparence n'est pas une promesse de campagne — c'est l'architecture même du système, détaillée sur la page {comment nous tenons nos promesses|/promesses}.",
      "La cotisation n'est pas qu'une contribution financière : c'est la clé de l'éligibilité. Sans cotisation à jour, aucune nomination, aucune candidature, aucun poste de direction. Cette règle s'applique à tous, du nouveau membre au cadre national, et alimente directement notre {sélection de candidats au mérite|/candidates}.",
      "Un dollar est une somme réelle pour beaucoup de familles congolaises ; c'est justement pour cela qu'elle est juste. Elle est accessible à l'ouvrier comme au cadre, et elle rend le parti redevable à des centaines de milliers de petits cotisants plutôt qu'à une poignée de gros donateurs.",
      "Cette indépendance financière protège la ligne du parti : impossible d'être acheté par un intérêt occulte quand votre trésorerie vient de la base et se lit en public. C'est l'indépendance politique par le nombre.",
      "Votre dollar compte. {Rejoignez le parti gratuitement|/register}, puis suivez le {registre public|/contributions} : vous verrez exactement où va chaque franc.",
    ],
    faq: [
      { q: "L'adhésion est-elle payante ?", a: "Non, l'adhésion est gratuite. La cotisation de 1 USD/mois (ou 12 USD/an) est volontaire et sert à financer le parti ; elle conditionne l'éligibilité aux candidatures et aux postes de direction." },
      { q: "Comment payer sa cotisation en RDC ?", a: "Par mobile money — M-Pesa, Orange Money ou Airtel Money. Chaque paiement est enregistré dans le registre public des cotisations, consultable par tous." },
      { q: "Où va l'argent des cotisations ?", a: "Dans un registre public affichant les totaux entrants, complété par des rapports de dépenses trimestriels. Aucune donnée personnelle n'est exposée : seuls les agrégats sont publics." },
    ],
  },
  {
    slug: 'snto-promesses-projets',
    title: 'SNTO : des promesses au développement en RDC',
    description:
      "Le système SNTO du Congo D'Abord transforme chaque promesse en projet de développement chiffré, financé et suivi jusqu'à la livraison, via 11 agents IA.",
    keywords: ['développement RDC', 'projets nationaux Congo', 'promesses électorales', 'infrastructure Congo', 'transformation nationale'],
    date: '2026-08-02',
    author: 'Le Congo D\'Abord',
    category: 'Développement',
    readMinutes: 7,
    related: ['parti-politique-ia-rdc', 'infrastructure-participative', '23-agents-ia-parti-congo'],
    content: [
      "Combien de promesses électorales avez-vous vu tenir en RDC ? Le {Système National de Transformation Opérationnel (SNTO)|/projects} existe pour une raison : qu'aucune promesse du Congo D'Abord ne se perde jamais entre le discours de campagne et la réalité du terrain.",
      "Le problème n'a jamais été le manque d'idées. C'est le trou noir entre l'annonce et la livraison, là où les projets disparaissent faute de budget crédible, de financement identifié ou de responsable nommé. Le SNTO comble ce trou en rendant chaque étape traçable.",
      "Le pipeline est simple et impitoyable : Manifeste → Programme → Projets → Livraison → Résultats → Réélection. Chaque étape a son agent IA. {L'Architecte du Manifeste|/projects/manifesto-architect} transforme la vision en programmes chiffrés ; le {Concepteur de Projets|/projects/project-designer} décompose chaque programme en projets finançables.",
      "Le {Costing National|/projects/national-costing} produit des budgets professionnels — CAPEX, OPEX, trois scénarios. Le {Courtier en Financement|/projects/funding-matchmaker} identifie les bailleurs adaptés — Banque Mondiale, BAD, financements PPP — avec un score de probabilité pour chacun, afin que le financement ne soit plus une loterie.",
      "Ensuite vient l'exécution : la {Structure de Livraison|/projects/delivery-structure} assigne des responsables à 7 niveaux, du national au communautaire, et {l'Affectation des Talents|/projects/talent-assignment} trouve le meilleur membre du parti pour diriger chaque projet, selon la même logique de mérite que la {sélection des candidats|/candidates}.",
      "Enfin, le {Centre de Commandement|/projects/command-centre} affiche tout en temps réel : projets livrés, budgets consommés, emplois créés, classement des provinces, performance des responsables. Quand nous gouvernerons, chaque citoyen pourra vérifier chaque promesse, comme il vérifie déjà nos {cotisations|/contributions}.",
      "La feuille de route couvre 10 ans : le premier mandat pour les fondations — routes, énergie, écoles, santé — le second pour la transformation : industrialisation, rail rapide, {villes intelligentes|/projects/development-strategist}. C'est un développement planifié, pas improvisé.",
      "Explorez le {SNTO complet|/projects} et voyez comment une promesse devient un chantier — puis un résultat.",
    ],
    faq: [
      { q: "Qu'est-ce que le SNTO ?", a: "Le Système National de Transformation Opérationnel : une chaîne de 11 agents IA qui convertit le manifeste du parti en projets chiffrés, financés, exécutés et suivis publiquement, du programme jusqu'aux résultats." },
      { q: "Comment le SNTO garantit-il qu'une promesse est tenue ?", a: "Chaque promesse traverse des étapes traçables (budget, financement, responsable, livraison) affichées dans un centre de commandement. Rien ne reste au stade du discours sans dossier vérifiable." },
      { q: "Qui finance les projets nationaux ?", a: "Un agent dédié identifie les bailleurs adaptés — Banque Mondiale, BAD, partenariats public-privé — avec un score de probabilité, en complément des ressources propres du parti." },
    ],
  },
  {
    slug: 'infrastructure-participative',
    title: 'Infrastructure en RDC : du problème local au projet',
    description:
      "Route, école, eau potable : Le Congo D'Abord transforme chaque besoin d'infrastructure signalé en dossier classé, chiffré et suivi jusqu'à la solution.",
    keywords: ['infrastructure RDC', 'développement local Congo', 'eau potable RDC', 'routes Congo', 'démocratie participative'],
    date: '2026-08-03',
    author: 'Le Congo D\'Abord',
    category: 'Développement',
    readMinutes: 5,
    related: ['snto-promesses-projets', 'parti-politique-ia-rdc', 'du-village-a-la-presidence-structure'],
    content: [
      "Dans chaque village congolais, on connaît les problèmes par cœur : la route impraticable à la saison des pluies, l'école dont le toit fuit, la source d'eau à deux heures de marche. Ce qui manque, ce n'est pas le diagnostic — c'est le chemin entre le problème et la solution.",
      "La plupart des besoins ne remontent jamais parce qu'il n'existe aucun canal fiable pour les faire connaître, les chiffrer et les prioriser. Résultat : les décisions se prennent loin du terrain, et les villages attendent des années pour des travaux qui n'arrivent pas.",
      "{L'Agent Infrastructure|/infrastructure} du Congo D'Abord crée ce canal. N'importe quel membre peut signaler un besoin local. L'IA le classe par sévérité — Critique, Élevé, Moyen, Faible — estime la population affectée, chiffre le coût de résolution et propose des solutions pragmatiques adaptées au contexte congolais.",
      "Ces dossiers alimentent directement le {SNTO|/projects} : les besoins les plus critiques deviennent des projets nationaux, avec budget, financement et responsables nommés. Le problème de votre village peut devenir une priorité nationale — parce qu'il est documenté, chiffré et visible de tous.",
      "C'est aussi cela, la {structure à 7 niveaux|/dashboard} : chaque village a une cellule, chaque cellule a une voix, et cette voix remonte jusqu'à la direction du parti. Où que vous viviez, votre {province|/province} pèse dans les décisions nationales.",
      "Cette approche transforme la relation entre le citoyen et la politique : on ne se contente plus de voter tous les cinq ans, on documente, on suit et on tient les responsables comptables entre les élections. C'est la démocratie participative appliquée au réel, pas un slogan.",
      "Prenons un exemple concret : une communauté signale un pont emporté par les pluies. L'IA estime les milliers de personnes coupées du marché et de l'école, chiffre la reconstruction et propose un calendrier. Le dossier devient vérifiable, comparable aux autres besoins du pays et défendable devant les bailleurs — au lieu de rester une doléance orale oubliée.",
      "Votre village mérite d'être entendu. {Devenez membre gratuitement|/register}, signalez vos besoins, et suivez leur progression en toute transparence.",
    ],
    faq: [
      { q: "Qui peut signaler un problème d'infrastructure ?", a: "Tout membre du parti, depuis n'importe quelle province. Le signalement est classé par l'IA selon sa gravité et la population concernée, puis chiffré et suivi." },
      { q: "Un besoin local peut-il vraiment devenir un projet national ?", a: "Oui. Les dossiers les plus critiques alimentent le SNTO et deviennent des projets avec budget, financement et responsable. La priorité vient de la gravité documentée, pas des relations." },
      { q: "Faut-il payer pour signaler un besoin ?", a: "Non. L'adhésion est gratuite et le signalement aussi. La cotisation de 1 USD/mois concerne l'éligibilité aux candidatures, pas la participation citoyenne." },
    ],
  },
  {
    slug: 'academie-politique-formation',
    title: 'Formation politique gratuite pour les Congolais',
    description:
      "14 modules de formation politique gratuite — leadership, gouvernance, finances publiques, éthique — pour former les cadres du Congo D'Abord, sans les acheter.",
    keywords: ['formation politique RDC', 'leadership Congo', 'académie politique', 'formation gratuite RDC', 'jeunesse congolaise'],
    date: '2026-08-03',
    author: 'Le Congo D\'Abord',
    category: 'Formation',
    readMinutes: 5,
    related: ['selection-candidats-merite', 'transparence-cotisations', 'jeunes-diplomes-sans-emploi-politique'],
    content: [
      "Un parti qui n'investit pas dans la formation de ses membres achète ses cadres ailleurs — avec tout ce que cela implique en dettes et en loyautés cachées. {L'Académie Politique|/training} du Congo D'Abord fait le pari inverse : former gratuitement chaque membre qui veut apprendre.",
      "En RDC, des millions de jeunes ont l'intelligence et l'énergie de diriger, mais pas l'accès aux savoirs politiques concrets. L'Académie ouvre cet accès à tous, gratuitement, en ligne comme sur mobile, pour que le talent ne dépende plus du carnet d'adresses.",
      "Le curriculum couvre 14 modules : leadership et prise de décision, gouvernance locale, finances publiques, communication politique, éthique et intégrité, droit électoral congolais, gestion de projets, mobilisation communautaire, et plus encore. Chaque module est ancré dans le contexte réel de la RDC.",
      "La formation n'est pas décorative : elle compte pour 10 % du {score de sélection des candidats|/candidates}. Un membre formé progresse dans le parti ; un membre non formé reste à la base. C'est la {méritocratie|/promesses} appliquée, module après module — un chemin vers le pouvoir ouvert par le travail, pas par les relations.",
      "L'IA personnalise chaque parcours : selon votre profil et vos ambitions, {l'Agent Académie|/training} recommande les modules prioritaires, l'ordre optimal et le temps nécessaire, avec l'impact estimé sur votre score. Vous savez exactement quoi apprendre pour avancer.",
      "Se former, c'est aussi se défendre : un citoyen qui comprend les finances publiques et le droit électoral est bien plus difficile à manipuler. L'éducation politique est la meilleure arme contre la démagogie et l'achat des consciences.",
      "Cette Académie sert enfin de vivier : c'est parmi les membres formés que le parti identifie ses futurs coordinateurs, ses candidats et ses gestionnaires de projets nationaux. Se former aujourd'hui, c'est se positionner pour les responsabilités de demain, dans sa {province|/province} comme au niveau national.",
      "{Inscrivez-vous gratuitement|/register}, commencez votre premier module dès aujourd'hui, et prenez votre place dans la transformation du Congo.",
    ],
    faq: [
      { q: "La formation de l'Académie Politique est-elle vraiment gratuite ?", a: "Oui, entièrement gratuite pour tous les membres. L'adhésion elle-même est gratuite ; il suffit de créer un compte pour accéder aux 14 modules." },
      { q: "À quoi sert la formation concrètement ?", a: "Elle compte pour 10 % du score de sélection des candidats et donne des compétences réelles : gouvernance, finances publiques, droit électoral, leadership. Se former, c'est progresser dans le parti." },
      { q: "Peut-on suivre les modules depuis un téléphone ?", a: "Oui, l'Académie est pensée pour le mobile, canal principal d'accès en RDC, avec des parcours personnalisés par l'IA selon votre profil et vos objectifs." },
    ],
  },
  {
    slug: '23-agents-ia-parti-congo',
    title: 'Les 23 agents IA qui font tourner le parti',
    description: "Inscription, candidats, formation, projets : les 23 agents IA du Congo D'Abord font tourner le parti 24h/24. L'IA propose, l'humain décide toujours.",
    keywords: ['agents IA parti', 'intelligence artificielle politique RDC', 'automatisation parti', "Congo D'Abord", 'IA Afrique'],
    date: '2026-08-04',
    author: "Le Congo D'Abord",
    category: 'Technologie',
    readMinutes: 6,
    related: ['parti-politique-ia-rdc', 'selection-candidats-merite', 'snto-promesses-projets'],
    content: [
      "Un parti politique moderne, c'est des milliers de décisions par jour. Au {Congo D'Abord|/}, 23 agents d'intelligence artificielle spécialisés portent cette charge — pour que les humains se concentrent sur ce qui compte : décider et servir les citoyens.",
      "Pourquoi automatiser ? Parce que la lenteur et l'opacité sont le terreau de la corruption. Quand une inscription traîne des semaines ou qu'un dossier disparaît dans un tiroir, une place s'ouvre pour le passe-droit. Des agents qui traitent tout, vite et de la même façon pour tous, ferment cette porte.",
      "Douze agents gèrent le parti au quotidien : validation des {inscriptions|/register}, cartographie des membres, {analyse des profils et scoring|/candidates}, {génération de politiques publiques|/policy}, priorisation des {besoins d'infrastructure|/infrastructure}, suivi des {cotisations|/contributions}, parcours de {formation personnalisés|/training}, gestion des cas d'{éthique|/ethics} et bien plus.",
      "Onze autres agents forment le {Système National de Transformation (SNTO)|/projects} : ils convertissent le manifeste en projets nationaux chiffrés, trouvent les financements, affectent les talents et suivent la livraison jusqu'au {tableau de bord exécutif|/projects/command-centre}.",
      "Le principe ne change jamais : l'IA propose, l'humain décide. Aucun agent ne prend de décision finale. L'intelligence artificielle élimine la lenteur et le favoritisme ; les organes élus du parti gardent seuls le pouvoir. La machine est un outil de justice, pas un dirigeant.",
      "Ces agents s'appuient sur plusieurs modèles d'IA de pointe, avec des garde-fous et une bascule automatique en cas de panne, pour que la plateforme reste disponible en continu. La fiabilité fait partie de la promesse.",
      "Et pour vous aider à mobiliser, un {moteur de croissance IA|/growth} génère posts, publicités et campagnes dans les cinq langues nationales. La technologie la plus avancée d'Afrique, au service d'un seul objectif : un Congo dirigé par la compétence.",
      "Découvrez ces agents en action : {créez votre compte gratuit|/register} et posez vos questions directement aux agents du parti.",
    ],
    faq: [
      { q: "Les agents IA prennent-ils des décisions à la place des dirigeants ?", a: "Non. Les 23 agents analysent, proposent et exécutent des tâches, mais toute décision finale revient aux organes élus du parti. L'IA propose, l'humain décide." },
      { q: "Que se passe-t-il si l'IA tombe en panne ?", a: "La plateforme utilise plusieurs modèles avec une bascule automatique et des garde-fous, de sorte que les services essentiels restent disponibles même si un fournisseur d'IA est indisponible." },
      { q: "En quoi l'automatisation réduit-elle la corruption ?", a: "En traitant chaque dossier vite et de manière identique pour tous, l'IA supprime les délais et l'opacité qui permettent les passe-droits. La transparence remplace le carnet d'adresses." },
    ],
  },
  {
    slug: 'du-village-a-la-presidence-structure',
    title: "La structure à 7 niveaux du Congo D'Abord en RDC",
    description: "La structure à 7 niveaux du Congo D'Abord relie 26 provinces, 145 territoires et des milliers de villages : chaque membre a sa place et sa voix.",
    keywords: ['structure parti RDC', 'organisation politique Congo', '26 provinces', 'village Congo', 'décentralisation RDC'],
    date: '2026-08-04',
    author: "Le Congo D'Abord",
    category: 'Structure',
    readMinutes: 5,
    related: ['parti-politique-ia-rdc', 'infrastructure-participative', 'diaspora-congolaise-engagement'],
    content: [
      "Dans la plupart des partis congolais, le village ne compte pas : tout se décide à Kinshasa, et l'intérieur du pays sert de réservoir de voix. Au {Congo D'Abord|/}, le village est le socle. Notre structure à 7 niveaux relie chaque citoyen, du hameau le plus reculé jusqu'à la Présidence.",
      "La hiérarchie est claire : National → Provincial (26 provinces) → Territoire/Ville (145 territoires, 33 villes) → Commune/Secteur/Chefferie → Quartier/Groupement → Cellule/Village → Diaspora. Chaque membre {inscrit|/register} est situé précisément dans cette structure, là où il vit réellement.",
      "Pourquoi est-ce déterminant ? Parce que le parti sait, en continu, combien de membres il compte dans chaque village, et cette information remonte jusqu'au {tableau de bord national|/dashboard}. Une organisation qui se connaît elle-même à ce niveau de détail peut répartir ses efforts avec justice, plutôt que de concentrer l'attention sur quelques grandes villes.",
      "Cette structure alimente tout le reste : la {sélection des candidats au mérite|/candidates} tient compte de la crédibilité locale, et les {besoins d'infrastructure|/infrastructure} signalés au niveau du village deviennent des projets nationaux via le {SNTO|/projects}. Rien ne se perd entre la base et le sommet.",
      "Elle protège aussi contre la confiscation du pouvoir : quand chaque échelon est peuplé de membres identifiés et de responsables choisis au mérite, il devient bien plus difficile pour un petit groupe de s'accaparer le parti. Le nombre et la traçabilité sont des garde-fous.",
      "Votre {province|/province} et votre village méritent d'être sur la carte, pas seulement le jour du vote. {Rejoignez le mouvement gratuitement|/register} et prenez votre place dans la structure.",
    ],
    faq: [
      { q: "Quels sont les 7 niveaux de la structure ?", a: "National, provincial (26 provinces), territoire/ville, commune/secteur/chefferie, quartier/groupement, cellule/village, et diaspora. Chaque membre est rattaché au niveau où il vit." },
      { q: "La diaspora fait-elle partie de la structure ?", a: "Oui, la diaspora est un niveau à part entière. Les Congolais de l'étranger s'inscrivent, cotisent et deviennent éligibles aux postes qui leur sont dédiés." },
      { q: "En quoi cette structure aide-t-elle mon village ?", a: "Elle donne à chaque village une cellule et une voix qui remonte jusqu'au sommet, et transforme les besoins locaux signalés en projets nationaux via le SNTO." },
    ],
  },
  {
    slug: 'cinq-langues-nationales-plateforme',
    title: 'Un parti dans vos 5 langues nationales en RDC',
    description: "Le Congo D'Abord est la première plateforme politique disponible dans les 5 langues nationales de la RDC : français, lingala, kikongo, tshiluba, kiswahili.",
    keywords: ['langues nationales RDC', 'Lingala politique', 'Kiswahili Congo', 'plateforme multilingue', 'inclusion RDC'],
    date: '2026-08-05',
    author: "Le Congo D'Abord",
    category: 'Inclusion',
    readMinutes: 4,
    related: ['du-village-a-la-presidence-structure', 'parti-politique-ia-rdc', 'diaspora-congolaise-engagement'],
    content: [
      "Un cultivateur du Kasaï et un commerçant de Goma ne parlent pas toujours la même langue. Au {Congo D'Abord|/}, ils utilisent pourtant la même plateforme — chacun dans la sienne. La langue cesse d'être une barrière à la participation politique.",
      "Trop souvent, la politique congolaise se fait en français, excluant de fait des millions de citoyens plus à l'aise dans leur langue maternelle. Réserver le débat à une seule langue, c'est réserver le pouvoir à une minorité. Nous refusons ce filtre.",
      "Français, lingala, kikongo, tshiluba et kiswahili : les cinq langues nationales de la RDC sont toutes disponibles, de l'{inscription|/register} jusqu'au {tableau de bord|/dashboard}. Vous choisissez au sommet de la page, et toute l'interface suit instantanément.",
      "Même le {moteur de communication IA|/growth} du parti génère les messages dans les cinq langues, avec le registre culturel adapté à chacune. Un discours pensé à Kinshasa peut toucher un village de l'Équateur dans sa langue maternelle, sans perdre son sens.",
      "L'inclusion linguistique compte aussi dans la {sélection des candidats|/candidates} : la maîtrise des langues fait partie des 8 critères de scoring. Parler à son peuple, dans sa langue, est une véritable compétence politique — pas un détail folklorique.",
      "Cette ouverture renforce l'unité nationale plutôt que de la diviser : quand chaque communauté peut participer dans sa langue, elle se sent pleinement partie prenante du même projet de {transformation du pays|/promesses}.",
      "Dans votre langue, votre voix porte plus loin. {Inscrivez-vous gratuitement|/register} et choisissez la langue qui est la vôtre.",
    ],
    faq: [
      { q: "Quelles langues la plateforme prend-elle en charge ?", a: "Les cinq langues nationales de la RDC : français, lingala, kikongo, tshiluba et kiswahili, de l'inscription jusqu'au tableau de bord." },
      { q: "L'IA communique-t-elle aussi dans ces langues ?", a: "Oui. Le moteur de communication génère posts, messages et campagnes dans les cinq langues, avec un registre culturel adapté à chacune." },
      { q: "La langue influence-t-elle la sélection des candidats ?", a: "La maîtrise des langues compte pour 5 % du score de mérite : savoir s'adresser à son peuple dans sa langue est reconnu comme une compétence politique." },
    ],
  },
  {
    slug: 'diaspora-congolaise-engagement',
    title: 'Diaspora congolaise : agir pour le pays de loin',
    description: "De Bruxelles à Montréal, la diaspora congolaise est pleinement intégrée au Congo D'Abord : cotisation en ligne, postes dédiés, mobilisation à distance.",
    keywords: ['diaspora congolaise', 'Congolais étranger', 'diaspora RDC politique', 'vote diaspora', 'engagement diaspora'],
    date: '2026-08-05',
    author: "Le Congo D'Abord",
    category: 'Diaspora',
    readMinutes: 5,
    related: ['du-village-a-la-presidence-structure', 'transparence-cotisations', 'cinq-langues-nationales-plateforme'],
    content: [
      "Des millions de Congolais vivent à l'étranger — et beaucoup veulent agir pour le pays sans savoir comment. Trop de partis ne les voient que comme un portefeuille à solliciter en période de campagne. Le {Congo D'Abord|/} fait de la diaspora le 7e niveau de sa structure, à part entière.",
      "Où que vous soyez — Afrique, Europe, Amériques, Asie, Océanie — vous vous {inscrivez en ligne gratuitement|/register}, vous {cotisez par mobile money ou carte|/contributions} (12 USD/an), et vous devenez éligible aux postes diaspora du parti. La distance ne vous relègue plus au rang de simple spectateur.",
      "La diaspora apporte deux forces rares : une capacité de cotisation plus élevée et un réseau international précieux — compétences, contacts, expériences de gouvernance observées ailleurs. Bien canalisées, ces forces peuvent accélérer la {transformation du pays|/promesses}.",
      "Mais l'argent ne donne aucun privilège : votre engagement compte autant que celui d'un membre à Kinshasa, ni plus ni moins. La {sélection des candidats|/candidates} applique exactement les mêmes critères de mérite à tous, où que l'on vive.",
      "Vous pouvez aussi mobiliser votre communauté avec les {outils de croissance IA|/growth} — dans les {cinq langues nationales|/cinq-langues-nationales-plateforme} — et {inviter vos proches|/invite} restés au pays ou installés ailleurs. Un membre actif de la diaspora peut en entraîner dix autres.",
      "Beaucoup ont quitté le Congo faute d'avenir ; participer à ce mouvement, c'est contribuer à construire le pays qui permettra, un jour, d'y revenir ou d'y investir sereinement.",
      "Loin du pays, proche du changement. {Rejoignez le mouvement depuis l'étranger|/register}.",
    ],
    faq: [
      { q: "Un Congolais de l'étranger peut-il adhérer ?", a: "Oui. La diaspora est un niveau à part entière : inscription en ligne gratuite, cotisation par mobile money ou carte, et éligibilité aux postes diaspora du parti." },
      { q: "La diaspora a-t-elle plus de pouvoir parce qu'elle cotise plus ?", a: "Non. La cotisation conditionne l'éligibilité, mais la sélection des responsables suit la même formule de mérite pour tous. L'argent n'achète aucun avantage." },
      { q: "Comment mobiliser ma communauté depuis l'étranger ?", a: "Via les outils de croissance IA (posts, campagnes multilingues) et le système d'invitation WhatsApp, qui permettent de recruter et de suivre les inscriptions." },
    ],
  },
  {
    slug: 'ethique-discipline-integrite-parti',
    title: "Éthique et intégrité : l'IA contre la corruption",
    description: "L'agent Éthique du Congo D'Abord analyse chaque cas d'intégrité avec des précédents comparables et des sanctions proportionnelles, contre la corruption.",
    keywords: ['éthique politique RDC', 'anti-corruption Congo', 'intégrité parti', 'discipline politique', 'gouvernance RDC'],
    date: '2026-08-06',
    author: "Le Congo D'Abord",
    category: 'Intégrité',
    readMinutes: 5,
    related: ['selection-candidats-merite', 'transparence-cotisations', 'securite-donnees-membres-chiffrement'],
    content: [
      "La corruption a détruit la confiance des Congolais envers la politique : à force de voir des responsables s'enrichir pendant que le pays s'appauvrit, beaucoup ont cessé de croire au changement. Le {Congo D'Abord|/} riposte avec une arme inhabituelle : un {agent IA dédié à l'éthique et à la discipline|/ethics}.",
      "L'idée n'est pas de remplacer la justice, mais de rendre la discipline interne cohérente et impossible à instrumentaliser. Dans trop de partis, les sanctions frappent les rivaux et épargnent les amis. Une analyse objective renverse cette logique.",
      "Chaque cas signalé est examiné selon des critères clairs : type de violation, gravité, précédents comparables, sanctions proportionnelles recommandées. Pas de règlements de comptes, pas d'impunité pour les puissants — une justice interne prévisible, où la même faute entraîne la même conséquence pour tous.",
      "Le score d'intégrité pèse pour 10 % dans la {sélection des candidats|/candidates}. Un membre dont la probité est entachée voit son éligibilité chuter, quel que soit son rang. L'intégrité n'est pas un discours : elle est mesurée et elle a des conséquences concrètes sur les carrières.",
      "Combinée à la {transparence financière totale|/contributions} — où chaque dollar cotisé est traçable dans un registre public — cette approche rend la corruption structurellement difficile. On ne dissimule pas ce qui est enregistré et visible ; la lumière est le meilleur désinfectant.",
      "Ce cadre protège aussi les membres honnêtes contre les accusations arbitraires : parce que chaque décision suit une méthode documentée, personne ne peut être broyé par une cabale. La discipline devient un bouclier, pas une arme.",
      "Un parti propre, c'est un parti qui se surveille sans complaisance. {Rejoignez un mouvement qui refuse la corruption|/register}.",
    ],
    faq: [
      { q: "L'IA sanctionne-t-elle elle-même les membres ?", a: "Non. L'agent Éthique analyse le cas et recommande une sanction proportionnelle avec des précédents comparables ; la décision finale appartient aux organes de discipline du parti." },
      { q: "Comment éviter que la discipline serve à régler des comptes ?", a: "En appliquant une méthode documentée et identique pour tous : même type de faute, même échelle de sanction, précédents à l'appui. La cohérence protège contre l'arbitraire." },
      { q: "L'intégrité compte-t-elle pour devenir candidat ?", a: "Oui, le score d'intégrité pèse 10 % dans la formule de sélection. Une probité entachée fait chuter l'éligibilité, quel que soit le rang du membre." },
    ],
  },
  {
    slug: 'moteur-croissance-ia-mobilisation',
    title: 'Marketing politique par IA : 10 outils en un clic',
    description: "Posts, publicités, emails, scripts vidéo, hashtags, analytique : le marketing politique professionnel du Congo D'Abord, entre les mains de chaque membre.",
    keywords: ['marketing politique RDC', 'mobilisation numérique', 'outils IA campagne', 'réseaux sociaux Congo', 'growth engine'],
    date: '2026-08-06',
    author: "Le Congo D'Abord",
    category: 'Mobilisation',
    readMinutes: 5,
    related: ['23-agents-ia-parti-congo', 'diaspora-congolaise-engagement', 'application-politique-telephone-rdc'],
    content: [
      "Mobiliser demande du temps, du talent et de l'argent — trois choses rares, surtout pour un jeune coordinateur de province. Le {moteur de croissance IA|/growth} du Congo D'Abord remplace ces trois obstacles par un simple clic.",
      "Historiquement, la communication politique efficace était réservée à ceux qui pouvaient payer une agence. Ce déséquilibre favorise l'argent au détriment des idées. En mettant des outils professionnels entre toutes les mains, on rééquilibre le jeu vers le mérite et l'engagement.",
      "Dix outils intégrés : générateur de posts sociaux (cinq langues), créateur de publicités, campagnes email, pages de destination, hashtags optimisés, scripts vidéo, plus l'analyse de performance, l'optimisation d'audience et les meilleurs horaires de publication pour le marché congolais.",
      "Un coordinateur local peut créer en trente secondes une campagne qui aurait coûté des centaines de dollars à une agence. C'est la démocratisation de la communication politique : chaque membre devient un ambassadeur efficace, capable de porter le message dans sa {province|/province} et sa langue.",
      "Ces outils s'articulent avec le {système de parrainage|/invite} : créez le message, partagez-le sur WhatsApp — canal roi en RDC — puis suivez les inscriptions qu'il génère. La croissance devient mesurable, et donc pilotable, au lieu de reposer sur l'intuition.",
      "Toute cette puissance sert une seule ligne : n'inventer aucune fausse statistique, ne manipuler personne, et faire connaître honnêtement un projet politique vérifiable. Un outil de mobilisation n'a de valeur que s'il sert la {transparence|/promesses}.",
      "Prêt à faire grandir le mouvement ? {Inscrivez-vous gratuitement|/register} et accédez au moteur de croissance.",
    ],
    faq: [
      { q: "Que contient le moteur de croissance IA ?", a: "Dix outils : posts sociaux multilingues, publicités, campagnes email, pages de destination, hashtags, scripts vidéo, analyse de performance, optimisation d'audience et meilleurs horaires de publication pour la RDC." },
      { q: "Faut-il des compétences techniques pour l'utiliser ?", a: "Non. En quelques secondes et sans expertise, un membre génère une campagne de qualité professionnelle, puis la partage sur WhatsApp et suit les inscriptions." },
      { q: "Ces outils peuvent-ils inventer des chiffres pour convaincre ?", a: "Non. Le moteur est explicitement contraint de ne jamais fabriquer de statistiques sur le parti ; il sert une communication honnête et vérifiable." },
    ],
  },
  {
    slug: 'centre-commandement-national-pilotage',
    title: 'Le tableau de bord national qui gouverne par les chiffres',
    description: "Projets livrés, budgets, emplois créés, classement des provinces et des ministres : le tableau de bord exécutif du Congo D'Abord rend la gouvernance vérifiable.",
    keywords: ['tableau de bord politique', 'pilotage national RDC', 'gouvernance données', 'performance ministres', 'transparence gouvernement'],
    date: '2026-08-07',
    author: "Le Congo D'Abord",
    category: 'Gouvernance',
    readMinutes: 5,
    related: ['snto-promesses-projets', '23-agents-ia-parti-congo', 'feuille-de-route-10-ans-mandats'],
    content: [
      "Gouverner sur des impressions, c'est ainsi qu'on gaspille un pays : on annonce, on inaugure, puis on oublie de mesurer. Quand nous gouvernerons, chaque citoyen pourra vérifier chaque promesse. Le {tableau de bord — Centre de Commandement National|/projects/command-centre} rend cela possible : tout le pays sur un écran.",
      "En temps réel s'affichent les indicateurs qui comptent : projets livrés contre projets en retard, budgets engagés et réellement dépensés, emplois créés, citoyens bénéficiaires, classement de performance des provinces et des ministres, et un score global d'avancement.",
      "Ces données ne sortent pas d'un discours : elles viennent directement du {SNTO|/projects}, qui suit chaque projet de la promesse à la livraison. Un responsable qui n'exécute pas apparaît dans le classement, en bas. La performance devient publique, donc politiquement responsable.",
      "Ce que l'on mesure, on l'améliore ; ce que l'on cache, on le laisse pourrir. Rendre visibles les retards et les réussites crée une pression saine vers l'exécution, et prive les mauvais gestionnaires de l'obscurité qui les protégeait.",
      "Les {tableaux de bord provinciaux et locaux|/dashboard} déclinent cette même transparence à chaque niveau de la {structure du parti|/du-village-a-la-presidence-structure}, si bien qu'un citoyen peut suivre aussi bien un chantier national qu'un projet de sa commune.",
      "Cette culture du chiffre prolonge celle du {registre public des cotisations|/contributions} : d'abord la transparence sur l'argent qui entre, ensuite la transparence sur les résultats qui sortent. Les deux bouts de la chaîne sont éclairés.",
      "La transparence n'est pas une promesse de campagne — c'est une architecture. {Rejoignez un parti qui accepte d'être mesuré|/register}.",
    ],
    faq: [
      { q: "Qu'affiche le tableau de bord national ?", a: "En temps réel : projets livrés ou en retard, budgets engagés et dépensés, emplois créés, bénéficiaires, et un classement de performance des provinces et des responsables." },
      { q: "D'où viennent ces chiffres ?", a: "Du SNTO, qui suit chaque projet de la promesse à la livraison. Les indicateurs sont générés par le pipeline de gestion, pas déclarés dans un discours." },
      { q: "Un citoyen ordinaire peut-il y accéder ?", a: "Oui : des tableaux de bord national, provinciaux et locaux déclinent la même transparence à chaque niveau, du grand chantier au projet communal." },
    ],
  },
  {
    slug: 'feuille-de-route-10-ans-mandats',
    title: 'Développement de la RDC : une feuille de route sur 10 ans',
    description: "Le plan de développement du Congo D'Abord sur 10 ans : les fondations d'abord (routes, énergie, écoles, santé), l'industrialisation ensuite (rail, villes).",
    keywords: ['développement RDC 10 ans', 'plan national Congo', 'industrialisation RDC', 'vision long terme', 'transformation nationale'],
    date: '2026-08-07',
    author: "Le Congo D'Abord",
    category: 'Vision',
    readMinutes: 6,
    related: ['snto-promesses-projets', 'centre-commandement-national-pilotage', 'engagement-politique-lubumbashi-katanga'],
    content: [
      "On ne transforme pas un pays en un seul mandat, et prétendre le contraire est la première des démagogies. Le {Congo D'Abord|/} planifie sur dix ans, avec un {agent IA dédié à la planification des deux mandats|/projects/second-term} qui séquence les chantiers dans le bon ordre.",
      "Pourquoi une planification aussi longue ? Parce que sans elle, chaque gouvernement recommence à zéro, abandonne les chantiers du précédent et gaspille des années. Une feuille de route publique force la continuité et permet aux citoyens de vérifier si le cap est tenu.",
      "Premier mandat (années 1 à 5) — les fondations : réhabilitation des routes, programme d'énergie solaire, rénovation des écoles, hôpitaux régionaux, gouvernement numérique. C'est l'infrastructure de base qui rend tout le reste possible ; sans elle, l'industrialisation reste un rêve.",
      "Second mandat (années 6 à 10) — la transformation : train rapide Kinshasa-Lubumbashi, infrastructure numérique nationale, zones de traitement local pour l'exportation minière, villes intelligentes. C'est l'industrialisation qui fait enfin décoller l'économie et crée des emplois durables.",
      "L'IA alloue chaque projet au bon mandat selon la faisabilité, le financement disponible et la capacité d'exécution, puis le tout est suivi dans le {tableau de bord national|/projects/command-centre} et nourri par le {système SNTO|/projects}. Chaque étape reste vérifiable.",
      "Cette vision se lit aussi au niveau local : les besoins signalés dans votre {province|/province} et les {projets d'infrastructure|/infrastructure} s'insèrent dans la feuille de route nationale, au lieu de dépendre du bon vouloir d'un ministre.",
      "Une vision qui dépasse les slogans électoraux. {Rejoignez la transformation à long terme|/register}.",
    ],
    faq: [
      { q: "Que prévoit le premier mandat ?", a: "Les fondations : routes, énergie solaire, écoles, hôpitaux régionaux et gouvernement numérique — l'infrastructure de base indispensable avant toute industrialisation." },
      { q: "Et le second mandat ?", a: "La transformation : rail rapide Kinshasa-Lubumbashi, infrastructure numérique nationale, traitement local des minerais et villes intelligentes, pour faire décoller l'économie." },
      { q: "Comment vérifier que le plan est respecté ?", a: "Chaque projet est suivi publiquement dans le tableau de bord national, de la promesse à la livraison. Les retards comme les réussites sont visibles." },
    ],
  },
  {
    slug: 'securite-donnees-membres-chiffrement',
    title: 'Sécurité des données : chiffrement bancaire des membres',
    description: "Sécurité des données au Congo D'Abord : chiffrement AES-256 de niveau bancaire et accès réservé aux humains. Protéger l'affiliation politique est un devoir.",
    keywords: ['sécurité données RDC', 'protection vie privée', 'chiffrement politique', 'données membres', 'cybersécurité Congo'],
    date: '2026-08-08',
    author: "Le Congo D'Abord",
    category: 'Sécurité',
    readMinutes: 5,
    related: ['ethique-discipline-integrite-parti', 'parti-politique-ia-rdc', 'application-politique-telephone-rdc'],
    content: [
      "En politique congolaise, une liste de membres tombée entre de mauvaises mains peut ruiner des vies : intimidations, représailles, pertes d'emploi. Le {Congo D'Abord|/} traite donc la sécurité des données comme une question de survie, pas de simple conformité administrative.",
      "Le principe de départ est clair : votre affiliation politique vous appartient, et à vous seul. Personne dans le parti, ni aucun tiers, ne devrait pouvoir en faire commerce ou la retourner contre vous. La technologie est là pour garantir ce droit, pas pour l'éroder.",
      "Concrètement, les informations sensibles — numéro d'identité, téléphone, adresse — sont chiffrées dans votre navigateur, avant même de quitter votre appareil, avec le standard AES-256-GCM, le même que celui des banques internationales. Elles voyagent et se stockent illisibles.",
      "L'agent de cybersécurité {Sentinel|/security} veille en permanence : il bloque les robots, les tentatives d'injection et les accès automatisés. Seuls des humains accèdent à la plateforme, et chaque {inscription|/register} est protégée par cette barrière.",
      "Cette sécurité renforce la {transparence des cotisations|/contributions} sans la contredire : les chiffres agrégés sont publics, mais l'identité de chaque membre reste privée. Transparence des flux financiers, confidentialité des personnes — les deux ne s'opposent pas, ils se complètent.",
      "C'est aussi une condition de la confiance de masse : beaucoup hésitent à s'engager par peur d'être fichés. En rendant l'adhésion sûre, on lève un frein réel à la participation, surtout pour les plus vulnérables.",
      "Votre engagement politique vous appartient. {Rejoignez une plateforme qui protège ses membres|/register}.",
    ],
    faq: [
      { q: "Comment mes données personnelles sont-elles protégées ?", a: "Les informations sensibles sont chiffrées dans votre navigateur avec le standard bancaire AES-256-GCM, avant de quitter votre appareil, puis stockées illisibles." },
      { q: "Qui peut voir que je suis membre ?", a: "Votre identité reste privée. Seuls des totaux agrégés (cotisations, effectifs) sont publics ; aucune donnée nominative n'est exposée." },
      { q: "La plateforme est-elle protégée contre le piratage ?", a: "Oui. L'agent Sentinel bloque en continu les robots, injections et accès automatisés, réservant l'accès aux humains vérifiés." },
    ],
  },
  {
    slug: 'un-dollar-pouvoir-mobile-money',
    title: '1 USD par mobile money : la politique accessible',
    description: "M-Pesa, Orange Money, Airtel Money : le mobile money rend l'engagement au Congo D'Abord accessible à chaque Congolais pour un dollar par mois, sans banque.",
    keywords: ['mobile money RDC', 'M-Pesa politique', 'cotisation 1 dollar', 'engagement accessible', 'Orange Money Congo'],
    date: '2026-08-08',
    author: "Le Congo D'Abord",
    category: 'Accessibilité',
    readMinutes: 4,
    related: ['transparence-cotisations', 'diaspora-congolaise-engagement', 'application-politique-telephone-rdc'],
    content: [
      "La politique congolaise a longtemps été réservée à ceux qui ont de l'argent et des relations. Le {Congo D'Abord|/} brise cette barrière avec un choix radicalement accessible : l'adhésion est gratuite, et la cotisation n'est que d'un dollar par mois, payable par mobile money.",
      "Pourquoi le mobile money ? Parce que c'est déjà l'argent du quotidien en RDC. M-Pesa, Orange Money, Airtel Money : ce sont les moyens que des dizaines de millions de Congolais utilisent chaque jour. Pas besoin de compte bancaire, pas de déplacement, pas de paperasse.",
      "Vous {cotisez depuis votre téléphone|/contributions} en quelques secondes, où que vous soyez, et chaque paiement entre aussitôt dans le registre public. La technologie ne sert pas ici à exclure les moins connectés, mais au contraire à les inclure.",
      "Ce dollar n'est pas qu'un paiement : c'est la clé de votre {éligibilité|/candidates}. Cotisation à jour signifie accès aux nominations, aux candidatures et aux postes de direction. Ainsi, la méritocratie devient réellement accessible à tous, pas seulement aux nantis.",
      "Un dollar est une somme réelle pour beaucoup de familles, et c'est justement ce qui rend le modèle juste : il est à la portée de l'ouvrier comme du cadre, et il rend le parti redevable à des centaines de milliers de petits cotisants plutôt qu'à quelques bailleurs.",
      "Pour ceux qui préfèrent, la formule annuelle à 12 USD réduit les frais et garantit un statut actif toute l'année. La {diaspora|/diaspora-congolaise-engagement}, elle, peut cotiser en ligne depuis l'étranger, par mobile money ou par carte.",
      "Un dollar pour reprendre votre pays en main. {Inscrivez-vous gratuitement et cotisez|/register} quand vous le décidez.",
    ],
    faq: [
      { q: "Quels moyens de paiement sont acceptés en RDC ?", a: "Le mobile money : M-Pesa, Orange Money et Airtel Money, sans compte bancaire ni déplacement. La diaspora peut aussi payer par carte en ligne." },
      { q: "Faut-il payer pour adhérer ?", a: "Non, l'adhésion est gratuite. La cotisation de 1 USD/mois (ou 12 USD/an) est volontaire et conditionne l'éligibilité aux candidatures et aux postes." },
      { q: "Un dollar par mois, est-ce vraiment accessible ?", a: "C'est la barrière d'entrée la plus basse de la politique congolaise, pensée pour être à la portée de l'ouvrier comme du cadre, et payable en quelques secondes depuis un téléphone." },
    ],
  },
  {
    slug: 'comment-devenir-candidat-rdc',
    title: 'Comment devenir candidat en RDC : le guide 2027',
    description: "Comment devenir candidat aux élections en RDC : les étapes concrètes, les critères de mérite et la façon dont le Congo D'Abord choisit ses candidats.",
    keywords: ['comment devenir candidat RDC', 'se présenter élections Congo', 'candidature politique RDC', 'devenir député Congo', 'élections 2028 RDC'],
    date: '2026-08-09',
    author: "Le Congo D'Abord",
    category: 'Guide',
    readMinutes: 6,
    related: ['selection-candidats-merite', 'academie-politique-formation', 'un-dollar-pouvoir-mobile-money'],
    content: [
      "Vous rêvez de servir votre pays comme élu ? En RDC, la question n'est plus seulement « qui connaissez-vous » mais « que valez-vous ». Voici, concrètement, comment devenir candidat au {Congo D'Abord|/}, en suivant un chemin clair et méritocratique plutôt qu'un réseau d'influence.",
      "Étape 1 : {inscrivez-vous gratuitement comme membre|/register} et complétez votre profil — éducation, expérience professionnelle, langues parlées, ancrage local. Ce profil est la matière première de votre évaluation ; plus il est complet et honnête, plus votre score reflète votre valeur réelle.",
      "Étape 2 : {mettez votre cotisation à jour|/contributions}, un dollar par mois, car sans cotisation il n'y a aucune éligibilité. Cette règle protège l'indépendance du parti et garantit que ses candidats émergent de sa base, pas de bailleurs extérieurs.",
      "Étape 3 : renforcez votre score via l'{Académie Politique|/training}. La formation compte pour 10 % de votre note de {sélection|/candidates}, aux côtés de l'éducation, de l'expérience, du leadership, de la crédibilité locale et de l'intégrité. C'est le levier le plus rapide pour progresser.",
      "Étape 4 : pour chaque poste, de chef de cellule à candidat député, l'IA propose les trois meilleurs profils aux organes élus du parti, qui décident. Votre score détaillé et ses justifications vous sont transparents : vous savez exactement où vous en êtes et quoi améliorer.",
      "Contrairement au système traditionnel, personne n'achète sa candidature ici : vous la méritez, critère après critère. C'est une garantie autant pour vous que pour les électeurs, qui savent que votre place a été gagnée. Découvrez la {formule de scoring complète|/selection-candidats-merite}.",
      "Votre parcours de candidat commence aujourd'hui. {Créez votre profil|/register} et visez le poste qui vous ressemble.",
    ],
    faq: [
      { q: "Quelles sont les étapes pour devenir candidat ?", a: "S'inscrire et compléter son profil, mettre sa cotisation à jour, renforcer son score via l'Académie Politique, puis être proposé par l'IA parmi les trois meilleurs profils du poste visé." },
      { q: "Faut-il de l'argent ou des relations pour être candidat ?", a: "Non. La candidature ne s'achète pas : elle dépend d'un score de mérite public (éducation, expérience, intégrité, ancrage local, formation) identique pour tous." },
      { q: "Peut-on connaître son score et le faire progresser ?", a: "Oui. Le score et ses justifications sont transparents, et la formation de l'Académie Politique est le moyen le plus rapide de l'améliorer." },
    ],
  },
  {
    slug: 'parti-politique-kinshasa-rejoindre',
    title: 'Rejoindre un parti politique à Kinshasa en 2027',
    description: "Comment rejoindre un parti politique à Kinshasa autrement : le Congo D'Abord propose inscription gratuite, cellule locale, formation et sélection au mérite.",
    keywords: ['parti politique Kinshasa', 'rejoindre parti Kinshasa', 'engagement politique Kinshasa', 'jeunesse Kinshasa politique', 'Kinshasa 2027'],
    date: '2026-08-09',
    author: "Le Congo D'Abord",
    category: 'Provinces',
    readMinutes: 4,
    related: ['du-village-a-la-presidence-structure', 'comment-devenir-candidat-rdc', 'jeunes-diplomes-sans-emploi-politique'],
    content: [
      "Kinshasa, plus de quinze millions d'habitants, cœur politique et économique de la RDC. C'est aussi là que la lassitude envers la vieille politique — promesses non tenues, achats de voix, clientélisme — est la plus vive. Le {Congo D'Abord|/} y propose une autre manière de s'engager.",
      "La capitale déborde de talents inexploités : diplômés au chômage, entrepreneurs débrouillards, leaders de quartier respectés. Le problème n'est pas le manque de compétence, mais l'absence d'un chemin honnête vers les responsabilités. C'est ce chemin que le parti ouvre.",
      "En tant que Kinois, vous vous {inscrivez gratuitement en quelques minutes|/register}, vous êtes rattaché à votre commune et à votre quartier dans la {structure du parti|/du-village-a-la-presidence-structure}, et vous rejoignez une cellule locale active près de chez vous.",
      "La {sélection au mérite|/candidates} donne enfin à ces talents un débouché sans piston ni argent : votre score dépend de votre formation, de votre expérience et de votre intégrité, pas de vos relations. À Kinshasa plus qu'ailleurs, cela change tout.",
      "Vous pouvez suivre l'{Académie Politique|/training} depuis votre téléphone, signaler les {problèmes d'infrastructure|/infrastructure} de votre quartier — voirie, eau, électricité — et {mobiliser votre réseau|/invite}. Dans une ville aussi dense et connectée, un membre actif peut en entraîner des dizaines.",
      "La capitale peut donner le ton au reste du pays : une cellule kinoise dynamique devient un modèle pour les autres {provinces|/province}. C'est ici que la dynamique nationale peut s'enclencher le plus vite.",
      "La transformation du Congo commence par sa capitale. {Rejoignez Le Congo D'Abord à Kinshasa|/register}.",
    ],
    faq: [
      { q: "Comment rejoindre le parti à Kinshasa ?", a: "En vous inscrivant gratuitement en ligne : vous êtes rattaché à votre commune et à votre quartier, puis intégré à une cellule locale active." },
      { q: "Faut-il payer pour s'engager à Kinshasa ?", a: "Non, l'adhésion est gratuite. La cotisation volontaire de 1 USD/mois ouvre l'éligibilité aux candidatures et aux postes de responsabilité." },
      { q: "Que puis-je faire concrètement une fois membre ?", a: "Suivre l'Académie Politique, signaler les problèmes d'infrastructure de votre quartier, mobiliser votre réseau et viser un poste via la sélection au mérite." },
    ],
  },
  {
    slug: 'engagement-politique-lubumbashi-katanga',
    title: 'Lubumbashi : rejoindre un parti qui sert le Katanga',
    description: "À Lubumbashi et dans le Haut-Katanga, rejoignez un parti qui veut transformer la richesse minière en développement local : le Congo D'Abord, au mérite.",
    keywords: ['parti politique Lubumbashi', 'Haut-Katanga politique', 'engagement Katanga', 'mines Congo développement', 'Lubumbashi 2027'],
    date: '2026-08-10',
    author: "Le Congo D'Abord",
    category: 'Provinces',
    readMinutes: 4,
    related: ['parti-politique-kinshasa-rejoindre', 'feuille-de-route-10-ans-mandats', 'goma-nord-kivu-paix-developpement'],
    content: [
      "Le Katanga produit une part immense du cuivre et du cobalt de la planète — des métaux indispensables à la transition énergétique mondiale. Pourtant, ses habitants en voient trop peu les bénéfices : routes défoncées, coupures d'électricité, hôpitaux sous-équipés. Le {Congo D'Abord|/} veut inverser cette injustice, en commençant par l'engagement citoyen.",
      "La richesse d'une région ne se transforme en développement que si ses habitants ont voix au chapitre. Tant que les décisions se prennent ailleurs et sans redevabilité, les minerais partent et la pauvreté reste. Redonner du pouvoir aux Katangais, c'est la première étape.",
      "À Lubumbashi et dans tout le Haut-Katanga, vous {rejoignez le parti gratuitement en ligne|/register} et intégrez la {structure locale|/du-village-a-la-presidence-structure}. Vos préoccupations remontent, documentées et chiffrées, jusqu'au {tableau de bord national|/dashboard}, au lieu de se perdre.",
      "Le {système SNTO|/projects} planifie précisément ce type de transformation : zones industrielles, traitement local des minerais pour créer de la valeur sur place, corridors d'exportation. Ce sont des projets chiffrés et suivis publiquement, pas des promesses de campagne.",
      "La {sélection au mérite|/candidates} valorise enfin l'expertise minière et industrielle de la région. Ingénieurs, cadres, techniciens et leaders communautaires du Katanga : votre compétence a désormais un débouché politique, sans avoir à acheter votre place.",
      "Le développement katangais s'inscrit dans la {feuille de route nationale sur dix ans|/feuille-de-route-10-ans-mandats} : d'abord les fondations, ensuite l'industrialisation qui garde la valeur au pays.",
      "Faites du Katanga un modèle de transformation, pas un simple gisement. {Rejoignez Le Congo D'Abord à Lubumbashi|/register}.",
    ],
    faq: [
      { q: "Comment s'engager avec le parti à Lubumbashi ?", a: "En rejoignant gratuitement en ligne : vous êtes rattaché à la structure locale du Haut-Katanga et vos préoccupations remontent au niveau national." },
      { q: "Le parti a-t-il un plan pour les minerais du Katanga ?", a: "Oui. Le SNTO planifie le traitement local des minerais, des zones industrielles et des corridors d'exportation, pour créer de la valeur et des emplois sur place." },
      { q: "L'expertise minière compte-t-elle pour un poste ?", a: "Absolument. La sélection au mérite valorise l'expérience professionnelle et l'ancrage local ; ingénieurs et cadres du secteur y trouvent un vrai débouché politique." },
    ],
  },
  {
    slug: 'goma-nord-kivu-paix-developpement',
    title: "Goma et le Nord-Kivu : la politique au service de la paix et du développement",
    description: "Dans une région marquée par les conflits, Le Congo D'Abord propose un engagement politique tourné vers la paix, la reconstruction et le développement local. Voici comment participer depuis Goma.",
    keywords: ['parti politique Goma', 'Nord-Kivu politique', 'paix Est Congo', 'développement Kivu', 'reconstruction RDC'],
    date: '2026-08-10',
    author: "Le Congo D'Abord",
    category: 'Provinces',
    readMinutes: 5,
    related: ['engagement-politique-lubumbashi-katanga', 'infrastructure-participative'],
    content: [
      "L'Est de la RDC a trop souffert. À Goma et dans le Nord-Kivu, l'engagement politique doit servir la paix et la reconstruction. Le {Congo D'Abord|/} en fait une priorité structurelle.",
      "Malgré les défis, vous pouvez {rejoindre le parti en ligne|/register} et faire entendre la voix du Kivu dans la {structure nationale|/du-village-a-la-presidence-structure} — chaque village compte, même dans les zones les plus difficiles.",
      "L'{Agent Infrastructure|/infrastructure} recense les besoins urgents de reconstruction (routes, écoles, eau, santé) et les transforme en projets prioritaires via le {SNTO|/projects}.",
      "La {sélection des candidats|/candidates} valorise la crédibilité locale et l'intégrité — exactement ce dont l'Est a besoin pour reconstruire la confiance envers ses dirigeants.",
      "Construisons la paix par la compétence et la transparence. {Rejoignez Le Congo D'Abord à Goma|/register}.",
    ],
  },
  {
    slug: 'jeunes-diplomes-sans-emploi-politique',
    title: "Jeune diplômé sans emploi en RDC ? Votre compétence a une valeur politique",
    description: "Des milliers de jeunes Congolais diplômés cherchent leur place. Le Congo D'Abord transforme votre formation en atout politique concret, avec un chemin clair vers les responsabilités.",
    keywords: ['jeunes diplômés RDC', 'chômage jeunes Congo', 'emploi jeunesse RDC', 'opportunité jeunes Congo', 'leadership jeune Afrique'],
    date: '2026-08-11',
    author: "Le Congo D'Abord",
    category: 'Jeunesse',
    readMinutes: 5,
    related: ['comment-devenir-candidat-rdc', 'academie-politique-formation'],
    content: [
      "Vous avez un diplôme mais pas d'emploi, et la politique semble fermée à ceux qui n'ont ni argent ni relations ? Le {Congo D'Abord|/} a été construit précisément pour vous.",
      "Ici, votre {éducation et vos compétences|/candidates} valent des points réels dans la sélection — l'éducation compte pour 15%, l'expérience pour 20%. Votre parcours n'est plus invisible, il est mesuré et valorisé.",
      "L'{Académie Politique|/training} vous forme gratuitement au leadership, à la gouvernance et aux finances publiques — 14 modules qui augmentent votre score et vos chances d'accéder aux responsabilités.",
      "Pour 1 USD par mois, vous {devenez éligible|/contributions} aux postes et candidatures. La barrière financière la plus basse de la politique congolaise, pensée pour la jeunesse.",
      "Votre diplôme n'est pas un papier inutile — c'est un capital politique. {Inscrivez-vous et faites-le valoir|/register}.",
    ],
  },
  {
    slug: 'femmes-leadership-politique-congo',
    title: "Femmes congolaises et leadership politique : briser le plafond par le mérite",
    description: "En RDC, les femmes restent sous-représentées en politique. Le Congo D'Abord applique une sélection au mérite qui ne connaît pas le genre — voici comment les femmes prennent leur place.",
    keywords: ['femmes politique RDC', 'leadership féminin Congo', 'parité RDC', 'femmes candidates Congo', 'égalité genre Afrique'],
    date: '2026-08-11',
    author: "Le Congo D'Abord",
    category: 'Inclusion',
    readMinutes: 5,
    related: ['jeunes-diplomes-sans-emploi-politique', 'selection-candidats-merite'],
    content: [
      "Les femmes congolaises portent une grande part de l'économie et de la société — mais restent trop rares aux postes de décision. Le {Congo D'Abord|/} change les règles du jeu.",
      "Notre {formule de sélection|/candidates} est aveugle au genre : elle mesure l'éducation, l'expérience, le leadership, la crédibilité locale et l'intégrité. Une femme compétente obtient le même score qu'un homme aux mêmes qualités — et le poste va au meilleur.",
      "L'{Académie Politique|/training} offre aux femmes les mêmes outils de progression, gratuitement. Et la {structure du parti|/du-village-a-la-presidence-structure} leur ouvre des rôles à chaque niveau, du village au national.",
      "Pour 1 USD par mois, chaque Congolaise devient {éligible|/contributions} aux candidatures. C'est l'accessibilité qui rend l'égalité réelle, pas seulement proclamée.",
      "Le Congo a besoin de toutes ses filles autant que de tous ses fils. {Rejoignez le mouvement|/register} et prenez la place que vous méritez.",
    ],
  },
  {
    slug: 'transparence-financement-partis-rdc',
    title: "Où va l'argent des partis politiques en RDC ? La réponse du Congo D'Abord",
    description: "Le financement opaque des partis nourrit la corruption en RDC. Découvrez comment Le Congo D'Abord rend chaque dollar traçable et redonne le pouvoir aux membres cotisants.",
    keywords: ['financement partis RDC', 'argent politique Congo', 'transparence financière parti', 'corruption financement', 'où va argent parti'],
    date: '2026-08-12',
    author: "Le Congo D'Abord",
    category: 'Transparence',
    readMinutes: 5,
    related: ['transparence-cotisations', 'ethique-discipline-integrite-parti'],
    content: [
      "Qui finance les partis congolais ? Trop souvent, personne ne le sait — et c'est justement le problème. L'argent occulte achète l'influence et corrompt les décisions. Le {Congo D'Abord|/} fait le choix inverse : la transparence totale.",
      "Le parti est financé par ses membres, 1 USD à la fois, via {mobile money traçable|/un-dollar-pouvoir-mobile-money}. Chaque paiement est enregistré, chaque statut est visible. Il n'y a pas de financier caché parce qu'il n'y a pas besoin de financier caché.",
      "Cette transparence des {cotisations|/contributions} se combine avec l'{Agent Éthique|/ethics} qui traque les manquements à l'intégrité. On ne peut ni cacher l'argent, ni cacher les fautes.",
      "Résultat : un parti qui appartient réellement à ses membres, pas à des bailleurs de l'ombre. Avec suffisamment de cotisants, le parti est totalement indépendant — l'indépendance par la base.",
      "Reprenez le contrôle du financement politique. {Rejoignez un parti 100% transparent|/register}.",
    ],
  },
  {
    slug: 'application-politique-telephone-rdc',
    title: "Faire de la politique depuis son téléphone en RDC : c'est désormais possible",
    description: "Inscription, cotisation, formation, mobilisation : tout Le Congo D'Abord tient dans votre téléphone. Découvrez la première plateforme politique 100% mobile de la RDC.",
    keywords: ['application politique RDC', 'politique smartphone Congo', 'plateforme mobile parti', 'engagement mobile RDC', 'politique en ligne Congo'],
    date: '2026-08-12',
    author: "Le Congo D'Abord",
    category: 'Technologie',
    readMinutes: 4,
    related: ['un-dollar-pouvoir-mobile-money', 'moteur-croissance-ia-mobilisation'],
    content: [
      "En RDC, le téléphone est le premier — souvent le seul — accès à internet. Le {Congo D'Abord|/} est pensé pour cela : tout se fait depuis votre mobile, sans ordinateur ni bureau.",
      "Vous {vous inscrivez|/register} en quelques minutes, vous {cotisez par mobile money|/contributions}, vous suivez l'{Académie Politique|/training} entre deux trajets, et vous {mobilisez sur WhatsApp|/invite} — tout dans votre poche.",
      "La plateforme est légère et rapide, optimisée pour les connexions 3G et le coût des données mobiles congolaises. Pas besoin d'un smartphone dernier cri pour participer à la transformation du pays.",
      "Même les {23 agents IA|/23-agents-ia-parti-congo} et le {moteur de croissance|/growth} sont accessibles depuis votre écran. La technologie la plus avancée d'Afrique, dans la main de chaque Congolais.",
      "La politique de votre pays, à portée de pouce. {Téléchargez votre avenir — inscrivez-vous|/register}.",
    ],
  },
  {
    slug: 'coordinateur-local-parti-role',
    title: "Devenir coordinateur local du parti : le rôle qui transforme votre communauté",
    description: "Les coordinateurs locaux sont l'épine dorsale du Congo D'Abord. Découvrez ce rôle, ses responsabilités et comment il vous positionne comme leader de votre communauté.",
    keywords: ['coordinateur local parti', 'leader communautaire RDC', 'responsable cellule parti', 'organiser communauté Congo', 'militant RDC'],
    date: '2026-08-13',
    author: "Le Congo D'Abord",
    category: 'Guide',
    readMinutes: 5,
    related: ['du-village-a-la-presidence-structure', 'jeunes-diplomes-sans-emploi-politique'],
    content: [
      "Chaque grand mouvement repose sur des personnes de terrain. Au {Congo D'Abord|/}, ce sont les coordinateurs locaux — les leaders qui font vivre le parti dans chaque village, quartier et commune.",
      "Un coordinateur accueille les nouveaux {membres|/register}, anime sa cellule dans la {structure à 7 niveaux|/du-village-a-la-presidence-structure}, remonte les {besoins d'infrastructure|/infrastructure} de sa communauté et organise la mobilisation locale.",
      "C'est aussi un tremplin : la crédibilité locale et le leadership comptent lourd dans la {sélection des candidats|/candidates}. Un bon coordinateur se construit un chemin naturel vers les responsabilités électives.",
      "Le parti vous outille : {formation gratuite|/training}, {outils de croissance IA|/growth} pour mobiliser, et un {tableau de bord|/dashboard} pour suivre votre communauté. Vous n'êtes jamais seul.",
      "Devenez le visage du changement dans votre communauté. {Inscrivez-vous et proposez-vous comme coordinateur|/register}.",
    ],
  },
  {
    slug: 'pourquoi-nouveau-parti-congo-2027',
    title: "Pourquoi un nouveau parti politique en RDC en 2027 ? La réponse honnête",
    description: "Encore un parti ? Non — un système d'exploitation politique. Découvrez ce qui rend Le Congo D'Abord fondamentalement différent de tout ce qui existe en RDC.",
    keywords: ['nouveau parti RDC 2027', 'pourquoi Congo D\'Abord', 'parti différent Congo', 'alternative politique RDC', 'renouveau politique Congo'],
    date: '2026-08-13',
    author: "Le Congo D'Abord",
    category: 'Vision',
    readMinutes: 6,
    related: ['parti-politique-ia-rdc', 'transparence-financement-partis-rdc', 'comment-devenir-candidat-rdc'],
    content: [
      "« Encore un parti ? » C'est la question légitime de tout Congolais fatigué des promesses. La réponse du {Congo D'Abord|/} est simple : nous ne sommes pas un parti de plus, nous sommes un système.",
      "Les partis traditionnels vendent des candidatures ; nous les {attribuons au mérite|/candidates}. Ils cachent leurs finances ; nous {traçons chaque dollar|/transparence-financement-partis-rdc}. Ils oublient le village ; nous {cartographions chaque citoyen|/du-village-a-la-presidence-structure}. Ils promettent ; nous {suivons chaque projet jusqu'à la livraison|/projects}.",
      "Vingt-trois {agents d'intelligence artificielle|/23-agents-ia-parti-congo} font tourner ce système 24h/24, dans 5 langues, avec une sécurité de niveau bancaire. Rien de comparable n'existe en Afrique politique.",
      "Et tout cela pour 1 USD par mois — la barrière d'entrée la plus basse du continent. La compétence remplace l'argent ; la transparence remplace l'opacité ; les données remplacent les impressions.",
      "2027 n'est pas juste une élection de plus. C'est l'occasion de changer la manière même de faire de la politique au Congo. {Rejoignez la différence|/register}.",
    ],
  },
  {
    slug: 'lingala-parti-ia-congo',
    lang: 'ln',
    title: "Congo Liboso: parti ya politiki ya liboso na RDC oyo esalisami na mayele ya masini (IA)",
    description: "Yeba ndenge Congo Liboso ezali kobongola politiki na Congo: kopona bato ya kokamba na mayele, mbongo ya polele, mpe misala ya ekolo. Kotala mpe kokota.",
    keywords: ['parti politiki Congo', 'Congo Liboso', 'politiki na Lingala', 'IA na Afrika', 'kokota parti Congo'],
    date: '2026-08-14',
    author: "Le Congo D'Abord",
    category: 'Lingala',
    readMinutes: 5,
    related: ['lingala-kokota-parti', 'parti-politique-ia-rdc'],
    content: [
      "Republika Demokratiki ya Congo ezali kokota na eleko ya sika ya politiki. {Congo Liboso|/} ezali parti ya politiki ya liboso ya bana-mboka oyo esalisami na mayele ya masini (IA) — ezali te lokola liloba mpamba, kasi lokola esaleli ya solo oyo ezali kosala lelo.",
      "Ntango nyonso, ba-agents ya IA 23 bazali kosala mpo na parti: koyamba {bakomeli ya sika|/register}, kotanga ba-CV mpe {kopona ba-candidats|/candidates} na motindo ya mayele, kosala {politiki ya ekolo|/policy}, mpe kolanda ba-cotisation ya {mbongo ya polele|/contributions}.",
      "Likambo ya ntina: IA epesaka toli, kasi bato nde bazwaka mokano. Masini moko te ezwaka mokano ya nsuka. Mayele ya masini elongolaka bolamu ya bato mpe bopotu; bakambi ya parti babatelaka bokonzi.",
      "Membre nyonso ekomamaka na molongo ya bikolo 7, kobanda na mboka tii na Bokonzi ya Ekolo — na bituka 26 nyonso. Tala {tableau ya ekolo|/dashboard} mpo na komona.",
      "Kokota na molongo lelo: {komikoma na ba-étapes 6 ya pete|/register} mpe zala moto ya mbongwana ya ekolo.",
    ],
  },
  {
    slug: 'lingala-kokota-parti',
    lang: 'ln',
    title: "Ndenge ya kokota na parti ya politiki na Congo: dolar moko (1 USD) na sanza",
    description: "Congo Liboso efungoli politiki na bana-mboka nyonso: kokota na Mobile Money, cotisation ya dolar moko na sanza, kopona na mayele. Yeba ndenge.",
    keywords: ['kokota parti Congo', 'cotisation dolar moko', 'Mobile Money politiki', 'politiki na Lingala', 'M-Pesa Congo'],
    date: '2026-08-14',
    author: "Le Congo D'Abord",
    category: 'Lingala',
    readMinutes: 4,
    related: ['lingala-parti-ia-congo', 'lingala-kopona-candidats'],
    content: [
      "Politiki na Congo ezalaki mpo na bato oyo bazali na mbongo. {Congo Liboso|/} ebuki lopango yango: dolar moko na sanza, ofuti na Mobile Money (M-Pesa, Orange Money, Airtel Money).",
      "Cotisation ezali te kaka mbongo: ezali fungola ya {kopona yo lokola candidat|/candidates}. Soki cotisation ezali sembo te, okoki kozwa mokumba te. Motindo yango ezali mpo na bato nyonso.",
      "Mpo na bato oyo balingi, cotisation ya mbula (12 USD) ekitisaka ba-frais mpe ebatelaka statut na yo mbula mobimba. Kokota na {kotanga na Académie|/training} mpo na komatisa score na yo.",
      "Dolar moko mpo na kozongisa ekolo na yo na maboko. {Komikoma mpe futa cotisation|/register}.",
    ],
  },
  {
    slug: 'lingala-kopona-candidats',
    lang: 'ln',
    title: "Suka ya bolamu ya bato: ndenge Congo Liboso eponaka ba-candidats na mayele",
    description: "Formule ya bopikami ya makambo 8: mayele, mosala, lokumu ya mboka, bokambi, cotisation, formation, sembo, minoko. Kopona ya polele koleka nyonso na Afrika.",
    keywords: ['kopona ba-candidats Congo', 'mérite politiki', 'maponami Congo', 'candidat na Lingala', 'politiki sembo'],
    date: '2026-08-13',
    author: "Le Congo D'Abord",
    category: 'Lingala',
    readMinutes: 5,
    related: ['lingala-kokota-parti', 'lingala-parti-ia-congo'],
    content: [
      "Na politiki ya kala ya Congo, ba-candidature esombamaka. Na {Congo Liboso|/}, esalemaka na bolamu. {Ndenge ya kopona ba-candidats|/candidates} etongami na makambo 8 ya polele oyo moto moko akoki kobongola te.",
      "Formule: Kelasi (15%) + Mosala (20%) + Lokumu ya mboka (15%) + Bokambi (15%) + Cotisation (10%) + {Formation|/training} (10%) + Sembo (10%) + Minoko (5%). Motango: 100.",
      "Mpo na mokumba nyonso, IA eponaka bato 3 ya malamu koleka mpe epesaka yango na bakambi ya parti, baye bazwaka mokano. Score na yo ezali polele — oyebi esika ozali mpe ndenge ya komata.",
      "Motindo ya makasi: soki {cotisation|/contributions} ezali sembo te, okozala candidat te. Motindo yango ezali mpo na bato nyonso.",
      "Tala soki okoki: {sala profil na yo|/register} mpe yeba score na yo.",
    ],
  },
  {
    slug: 'lingala-diaspora-congo',
    lang: 'ln',
    title: "Bana-Congo ya libanda: bosala mpo na ekolo kozanga kotika mboka na bino",
    description: "Kobanda na Bruxelles tii na Montréal, Congo Liboso eyambi diaspora: voti na mosika, cotisation na internet, mikumba ya parti. Yeba ndenge ya kosangana.",
    keywords: ['diaspora Congo', 'bana-Congo libanda', 'diaspora politiki', 'voti diaspora', 'Lingala politiki'],
    date: '2026-08-13',
    author: "Le Congo D'Abord",
    category: 'Lingala',
    readMinutes: 4,
    related: ['lingala-parti-ia-congo', 'lingala-kokota-parti'],
    content: [
      "Bana-Congo ebele bazali na libanda — mpe mingi balingi kosala mpo na ekolo kasi bayebi ndenge te. {Congo Liboso|/} esali diaspora molongo ya 7 ya struktire na yango.",
      "Esika nyonso ozali — Afrika, Mpoto, Amerika, Azia — {okomikoma na internet|/register}, {ofuti cotisation na Mobile Money to carte|/contributions} (12 USD na mbula), mpe okoki kozwa mikumba ya diaspora.",
      "Diaspora ezali na nguya ya cotisation mpe ba-réseaux ya mokili. Bosalisi na bino ezali na ntina lokola membre ya Kinshasa — {kopona ba-candidats|/candidates} esalelaka motindo moko mpo na bato nyonso.",
      "Mosika na mboka, pene na mbongwana. {Kokota na molongo kobanda na libanda|/register}.",
    ],
  },
  {
    slug: 'lingala-mpo-na-nini-parti-sika',
    lang: 'ln',
    title: "Mpo na nini parti ya sika na Congo na 2027? Eyano ya solo",
    description: "Parti mosusu? Te — esaleli ya politiki. Yeba likambo oyo ekesenisa Congo Liboso na nyonso oyo ezali na Congo.",
    keywords: ['parti sika Congo 2027', 'mpo na nini Congo Liboso', 'parti mosusu Congo', 'mbongwana politiki', 'Lingala politiki'],
    date: '2026-08-12',
    author: "Le Congo D'Abord",
    category: 'Lingala',
    readMinutes: 5,
    related: ['lingala-parti-ia-congo', 'lingala-kopona-candidats'],
    content: [
      "«Parti mosusu?» Ezali motuna ya solo ya moto nyonso ya Congo oyo alembi bilaka. Eyano ya {Congo Liboso|/} ezali pete: tozali parti mosusu te, tozali esaleli.",
      "Ba-parti ya kala batekaka ba-candidature; biso {topesaka yango na bolamu|/candidates}. Bango babombaka mbongo; biso {tolandaka dolar nyonso|/contributions}. Bango babosanaka mboka; biso {tokomaka moto nyonso|/register}.",
      "Ba-agents ya IA 23 basalaka esaleli oyo ntango nyonso, na minoko 5, na bokengeli ya makasi. Eloko ya lolenge yango ezali na Afrika te.",
      "Mpe nyonso wana mpo na dolar moko na sanza — lopango ya nse koleka na kontinent. Bolamu ekitisaka mbongo; polele ekitisaka bopotu.",
      "2027 ezali kaka maponami mosusu te. Ezali libaku ya kobongola ndenge ya kosala politiki na Congo. {Kokota na bokeseni|/register}.",
    ],
  },
  {
    slug: 'swahili-chama-ia-congo',
    lang: 'sw',
    title: "Congo Kwanza: chama cha kwanza cha kisiasa DRC kinachotumia akili bandia (AI)",
    description: "Jifunze jinsi Congo Kwanza inavyobadilisha siasa Congo: kuchagua viongozi kwa ustadi, uwazi wa fedha, na miradi ya taifa. Angalia na ujiunge.",
    keywords: ['chama cha kisiasa Congo', 'Congo Kwanza', 'siasa kwa Kiswahili', 'AI Afrika', 'kujiunga chama Congo'],
    date: '2026-08-14',
    author: "Le Congo D'Abord",
    category: 'Kiswahili',
    readMinutes: 5,
    related: ['swahili-jiunge-chama', 'parti-politique-ia-rdc'],
    content: [
      "Jamhuri ya Kidemokrasia ya Congo inaingia katika enzi mpya ya kisiasa. {Congo Kwanza|/} ni chama cha kwanza cha kisiasa kinachoongozwa na raia na kuimarishwa kwa akili bandia (AI) — si kauli mbiu tu, bali chombo halisi kinachofanya kazi leo.",
      "Kila wakati, mawakala 23 wa AI hufanya kazi kwa ajili ya chama: kupokea {wanachama wapya|/register}, kuchambua CV na {kuchagua wagombea|/candidates} kwa ustadi, kutunga {sera za taifa|/policy}, na kufuatilia michango ya {fedha kwa uwazi|/contributions}.",
      "Kanuni muhimu: AI hupendekeza, lakini binadamu ndio huamua. Hakuna mashine inayofanya uamuzi wa mwisho. Akili bandia huondoa upendeleo na ufisadi; viongozi wa chama hubaki na madaraka.",
      "Kila mwanachama husajiliwa katika muundo wa ngazi 7, kuanzia kijiji hadi Urais — katika majimbo yote 26. Tazama {dashibodi ya taifa|/dashboard} kuona.",
      "Jiunge na harakati leo: {jisajili kwa hatua 6 rahisi|/register} na uwe sehemu ya mabadiliko ya taifa.",
    ],
  },
  {
    slug: 'swahili-jiunge-chama',
    lang: 'sw',
    title: "Jinsi ya kujiunga na chama cha kisiasa Congo: dola moja (1 USD) kwa mwezi",
    description: "Congo Kwanza inafungua siasa kwa raia wote: kujiunga kwa Mobile Money, mchango wa dola moja kwa mwezi, uchaguzi kwa ustadi. Jifunze jinsi.",
    keywords: ['kujiunga chama Congo', 'mchango dola moja', 'Mobile Money siasa', 'siasa Kiswahili', 'M-Pesa Congo'],
    date: '2026-08-14',
    author: "Le Congo D'Abord",
    category: 'Kiswahili',
    readMinutes: 4,
    related: ['swahili-chama-ia-congo', 'swahili-chagua-wagombea'],
    content: [
      "Siasa Congo ilikuwa kwa ajili ya wenye fedha. {Congo Kwanza|/} imevunja kizuizi hicho: dola moja kwa mwezi, unalipa kwa Mobile Money (M-Pesa, Orange Money, Airtel Money).",
      "Mchango si fedha tu: ni ufunguo wa {kuchaguliwa kama mgombea|/candidates}. Bila mchango uliolipwa, huwezi kupata wadhifa. Kanuni hii ni kwa wote sawa.",
      "Kwa wanaopenda, mchango wa mwaka (12 USD) hupunguza gharama na kuhakikisha hadhi yako mwaka mzima. Jiunge kwa {kusoma katika Chuo|/training} ili kuongeza alama zako.",
      "Dola moja kurudisha nchi yako mikononi. {Jisajili na ulipe mchango|/register}.",
    ],
  },
  {
    slug: 'swahili-chagua-wagombea',
    lang: 'sw',
    title: "Mwisho wa upendeleo: jinsi Congo Kwanza inavyochagua wagombea kwa ustadi",
    description: "Kanuni ya alama za vigezo 8: elimu, uzoefu, uaminifu wa kienyeji, uongozi, mchango, mafunzo, uadilifu, lugha. Uchaguzi wazi zaidi kuliko wote Afrika.",
    keywords: ['kuchagua wagombea Congo', 'ustadi siasa', 'uchaguzi Congo', 'mgombea Kiswahili', 'siasa uadilifu'],
    date: '2026-08-13',
    author: "Le Congo D'Abord",
    category: 'Kiswahili',
    readMinutes: 5,
    related: ['swahili-jiunge-chama', 'swahili-chama-ia-congo'],
    content: [
      "Katika siasa za zamani za Congo, ugombea ununuliwa. Katika {Congo Kwanza|/}, unapatikana kwa ustadi. {Jinsi ya kuchagua wagombea|/candidates} imejengwa juu ya vigezo 8 vilivyo wazi ambavyo hakuna mtu anayeweza kubadilisha.",
      "Kanuni: Elimu (15%) + Uzoefu (20%) + Uaminifu wa kienyeji (15%) + Uongozi (15%) + Mchango (10%) + {Mafunzo|/training} (10%) + Uadilifu (10%) + Lugha (5%). Jumla: 100.",
      "Kwa kila wadhifa, AI huchagua watu 3 bora na kuwapa viongozi wa chama, ambao huamua. Alama zako ni wazi — unajua ulipo na jinsi ya kupanda.",
      "Kanuni isiyobadilika: bila {mchango|/contributions} uliolipwa, hutakuwa mgombea. Kanuni hii ni kwa wote.",
      "Angalia kama unastahili: {tengeneza wasifu wako|/register} na ujue alama zako.",
    ],
  },
  {
    slug: 'swahili-vijana-ajira-siasa',
    lang: 'sw',
    title: "Kijana msomi usiye na ajira Congo? Ustadi wako una thamani ya kisiasa",
    description: "Maelfu ya vijana wasomi wa Congo wanatafuta nafasi zao. Congo Kwanza inabadilisha elimu yako kuwa faida ya kisiasa halisi, kwa njia wazi kuelekea uongozi.",
    keywords: ['vijana wasomi Congo', 'ukosefu ajira vijana', 'ajira vijana Congo', 'nafasi vijana Congo', 'uongozi kijana Afrika'],
    date: '2026-08-13',
    author: "Le Congo D'Abord",
    category: 'Kiswahili',
    readMinutes: 5,
    related: ['swahili-chagua-wagombea', 'swahili-jiunge-chama'],
    content: [
      "Una shahada lakini huna ajira, na siasa inaonekana imefungwa kwa wasio na fedha wala uhusiano? {Congo Kwanza|/} ilijengwa hasa kwa ajili yako.",
      "Hapa, {elimu na ustadi wako|/candidates} vina thamani halisi katika uchaguzi — elimu ni 15%, uzoefu ni 20%. Safari yako haionekani tena bali inapimwa na kuthaminiwa.",
      "{Chuo cha Siasa|/training} kinakufundisha bure uongozi, utawala na fedha za umma — masomo 14 yanayoongeza alama zako na nafasi zako za kupata madaraka.",
      "Kwa dola moja kwa mwezi, {unakuwa na haki|/contributions} ya wadhifa na ugombea. Kizuizi cha chini kabisa cha fedha katika siasa za Congo, kilichoundwa kwa ajili ya vijana.",
      "Shahada yako si karatasi bure — ni mtaji wa kisiasa. {Jisajili na uithamini|/register}.",
    ],
  },
];

export function getPostBySlug(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find(p => p.slug === slug);
}
