/**
 * Blog SEO — Le Congo D'Abord
 *
 * Each article targets specific DRC political search keywords and contains
 * dense internal links (dynamic hyperlinks) to platform pages, plus
 * cross-links between related articles. Content blocks support inline
 * links via the {text|href} token syntax rendered by the blog pages.
 */

export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  keywords: string[];
  date: string;
  author: string;
  category: string;
  readMinutes: number;
  related: string[]; // slugs — dynamic cross-linking between articles
  content: string[]; // paragraphs; {text|/path} tokens become hyperlinks
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: 'parti-politique-ia-rdc',
    title: "Le premier parti politique propulsé par l'IA en RDC : comment ça marche",
    description:
      "Découvrez comment Le Congo D'Abord utilise 23 agents d'intelligence artificielle pour transformer la politique congolaise : sélection des candidats au mérite, transparence financière totale et projets nationaux suivis en temps réel.",
    keywords: ['parti politique RDC', 'intelligence artificielle Congo', 'politique congolaise', 'Congo D\'Abord', 'IA Afrique'],
    date: '2026-08-01',
    author: 'Le Congo D\'Abord',
    category: 'Innovation',
    readMinutes: 6,
    related: ['selection-candidats-merite', 'transparence-cotisations'],
    content: [
      "La République Démocratique du Congo entre dans une nouvelle ère politique. {Le Congo D'Abord|/} est le premier parti politique congolais dirigé par des citoyens et renforcé par l'intelligence artificielle — pas comme un slogan, mais comme une infrastructure réelle qui fonctionne aujourd'hui.",
      "Concrètement, {23 agents IA spécialisés|/projects} travaillent pour le parti 24 heures sur 24 : validation des {inscriptions de membres|/register}, cartographie des adhérents dans les 26 provinces, {analyse des CV et sélection des candidats|/candidates}, génération de {politiques publiques|/policy}, priorisation des {besoins d'infrastructure|/infrastructure} signalés par les citoyens, et bien plus.",
      "Le principe fondamental ne change jamais : l'IA propose, les humains décident. Aucune décision finale n'est prise par une machine. L'intelligence artificielle élimine le favoritisme et l'arbitraire — les organes du parti gardent le pouvoir de décision.",
      "Chaque membre est enregistré dans une structure à 7 niveaux, du village jusqu'à la présidence, en passant par les territoires, communes et quartiers. La diaspora congolaise d'Afrique, d'Europe, des Amériques et d'Asie est pleinement intégrée. Consultez le {tableau de bord national|/dashboard} pour voir la structure en action.",
      "Et parce que la confiance se mérite, toutes les données sensibles des membres sont protégées par un chiffrement AES-256 de niveau bancaire — le même standard que les institutions financières internationales.",
      "Rejoignez le mouvement dès aujourd'hui : {inscrivez-vous en 6 étapes simples|/register} et devenez acteur de la transformation nationale.",
    ],
  },
  {
    slug: 'selection-candidats-merite',
    title: 'Fin du favoritisme : comment nos candidats sont sélectionnés au mérite',
    description:
      "La formule de scoring à 8 critères du Congo D'Abord : éducation, expérience, crédibilité locale, leadership, cotisation, formation, intégrité et langues. Découvrez la sélection politique la plus transparente d'Afrique.",
    keywords: ['candidats élections RDC', 'méritocratie Congo', 'sélection candidats', 'élections 2028 RDC', 'scoring politique'],
    date: '2026-08-01',
    author: 'Le Congo D\'Abord',
    category: 'Transparence',
    readMinutes: 5,
    related: ['parti-politique-ia-rdc', 'academie-politique-formation'],
    content: [
      "Dans la politique congolaise traditionnelle, les candidatures s'achètent. Au {Congo D'Abord|/}, elles se méritent. Notre {système de sélection des candidats|/candidates} repose sur une formule publique à 8 critères que personne — pas même le fondateur — ne peut contourner.",
      "La formule : Éducation (15%) + Expérience professionnelle (20%) + Crédibilité locale (15%) + Leadership (15%) + Statut de cotisation (10%) + {Formation complétée|/training} (10%) + Score d'intégrité (10%) + Capacité linguistique (5%). Total : 100 points.",
      "Pour chaque poste — du chef de cellule au candidat député — l'intelligence artificielle analyse tous les profils éligibles et propose les 3 meilleurs, avec scores détaillés et justifications. Les organes du parti choisissent parmi ces trois. C'est la fin des parachutages.",
      "Une règle est inviolable : sans {cotisation à jour|/contributions}, aucune éligibilité. Un dollar par mois — la cotisation la plus accessible du pays — garantit que le parti appartient à ses membres cotisants, pas à des financiers de l'ombre.",
      "Chaque membre peut améliorer son score en suivant les {14 modules de l'Académie Politique|/training} : leadership, gouvernance locale, finances publiques, éthique. Votre avenir politique dépend de votre travail, pas de vos connexions.",
      "Vérifiez votre éligibilité : {créez votre profil dès maintenant|/register} et découvrez votre score.",
    ],
  },
  {
    slug: 'transparence-cotisations',
    title: 'Un dollar par mois : la cotisation qui change la politique congolaise',
    description:
      "Pourquoi la cotisation de 1 USD/mois du Congo D'Abord est révolutionnaire : transparence financière totale, indépendance vis-à-vis des financiers occultes, et un parti qui appartient réellement à ses membres.",
    keywords: ['cotisation parti politique', 'financement politique RDC', 'transparence Congo', 'mobile money RDC', 'adhésion parti'],
    date: '2026-08-02',
    author: 'Le Congo D\'Abord',
    category: 'Transparence',
    readMinutes: 4,
    related: ['selection-candidats-merite', 'parti-politique-ia-rdc'],
    content: [
      "Qui finance un parti le contrôle. C'est pourquoi {Le Congo D'Abord|/} a fait un choix radical : le parti est financé par ses membres, à raison d'un dollar par mois — ou 12 dollars par an, la formule recommandée.",
      "Chaque paiement passe par mobile money (M-Pesa, Orange Money, Airtel Money) et est enregistré dans le {système de suivi des cotisations|/contributions}. Chaque membre voit son statut. Chaque franc est traçable. La transparence n'est pas une promesse — c'est l'architecture même du système.",
      "La cotisation n'est pas qu'une contribution financière : c'est la clé de l'éligibilité. Sans cotisation à jour, aucune nomination, aucune candidature, aucun poste de direction. Cette règle s'applique à tous, du nouveau membre au cadre national. Découvrez comment cela alimente notre {sélection de candidats au mérite|/candidates}.",
      "Avec 100 000 membres cotisants, le parti dispose de 100 000 dollars mensuels — sans devoir un seul franc à un financier occulte. C'est l'indépendance politique par la base.",
      "Votre dollar compte. {Rejoignez le parti|/register} et participez au premier financement politique 100% transparent de la RDC.",
    ],
  },
  {
    slug: 'snto-promesses-projets',
    title: 'SNTO : le système qui transforme les promesses électorales en projets réels',
    description:
      "Manifeste → Programme → Projets → Livraison → Résultats. Le Système National de Transformation Opérationnel du Congo D'Abord suit chaque promesse jusqu'à sa réalisation, avec 11 agents IA dédiés.",
    keywords: ['développement RDC', 'projets nationaux Congo', 'promesses électorales', 'infrastructure Congo', 'transformation nationale'],
    date: '2026-08-02',
    author: 'Le Congo D\'Abord',
    category: 'Développement',
    readMinutes: 7,
    related: ['parti-politique-ia-rdc', 'infrastructure-participative'],
    content: [
      "Combien de promesses électorales avez-vous vu tenir en RDC ? Le {Système National de Transformation Opérationnel (SNTO)|/projects} existe pour une raison : qu'aucune promesse du Congo D'Abord ne se perde jamais entre le discours et la réalité.",
      "Le pipeline est simple et impitoyable : Manifeste → Programme → Projets → Livraison → Résultats → Réélection. Chaque étape a son agent IA. {L'Architecte du Manifeste|/projects/manifesto-architect} transforme la vision en programmes chiffrés. Le {Concepteur de Projets|/projects/project-designer} décompose chaque programme en projets finançables.",
      "Le {Costing National|/projects/national-costing} produit des budgets professionnels — CAPEX, OPEX, trois scénarios. Le {Courtier en Financement|/projects/funding-matchmaker} identifie les bailleurs adaptés : Banque Mondiale, BAD, financements PPP, avec un score de probabilité pour chacun.",
      "Ensuite vient l'exécution : la {Structure de Livraison|/projects/delivery-structure} assigne des responsables à 7 niveaux — du politique au communautaire — et {l'Affectation des Talents|/projects/talent-assignment} trouve le meilleur membre du parti pour diriger chaque projet.",
      "Enfin, le {Centre de Commandement|/projects/command-centre} affiche tout en temps réel : projets livrés, budgets, emplois créés, classement des provinces, performance des ministres. Quand nous gouvernerons, chaque citoyen pourra vérifier chaque promesse.",
      "La feuille de route couvre 10 ans : le premier mandat pour les fondations (routes, énergie, écoles, santé), le second pour la transformation (industrialisation, rail rapide, {villes intelligentes|/projects/development-strategist}). Explorez le {SNTO complet|/projects}.",
    ],
  },
  {
    slug: 'infrastructure-participative',
    title: "Votre village a un problème ? L'IA en fait un projet d'infrastructure",
    description:
      "Route coupée, école sans toit, pas d'eau potable : avec Le Congo D'Abord, chaque problème local signalé devient un dossier d'infrastructure classé, chiffré et suivi. La démocratie participative version RDC.",
    keywords: ['infrastructure RDC', 'développement local Congo', 'eau potable RDC', 'routes Congo', 'démocratie participative'],
    date: '2026-08-03',
    author: 'Le Congo D\'Abord',
    category: 'Développement',
    readMinutes: 5,
    related: ['snto-promesses-projets', 'parti-politique-ia-rdc'],
    content: [
      "Dans chaque village congolais, on connaît les problèmes par cœur : la route impraticable à la saison des pluies, l'école dont le toit fuit, la source d'eau à deux heures de marche. Ce qui manque, ce n'est pas le diagnostic — c'est le chemin entre le problème et la solution.",
      "{L'Agent Infrastructure|/infrastructure} du Congo D'Abord crée ce chemin. N'importe quel membre peut signaler un besoin local. L'IA le classe par sévérité (Critique, Élevé, Moyen, Faible), estime la population affectée, chiffre le coût de résolution et propose des solutions pragmatiques adaptées au contexte congolais.",
      "Ces dossiers alimentent directement le {SNTO|/projects} : les besoins les plus critiques deviennent des projets nationaux, avec budget, financement et responsables. Le problème de votre village peut devenir une priorité nationale — parce qu'il est documenté, chiffré et visible.",
      "C'est aussi cela, la structure à 7 niveaux : chaque village a une cellule, chaque cellule a une voix, et cette voix remonte jusqu'au {tableau de bord national|/dashboard} que consulte la direction du parti.",
      "Votre village mérite d'être entendu. {Devenez membre|/register}, signalez vos besoins, et suivez leur progression en toute transparence.",
    ],
  },
  {
    slug: 'academie-politique-formation',
    title: "L'Académie Politique : former la prochaine génération de dirigeants congolais",
    description:
      "14 modules gratuits de formation politique : leadership, gouvernance, finances publiques, éthique, droit électoral. Comment Le Congo D'Abord forme ses membres au lieu d'acheter ses cadres.",
    keywords: ['formation politique RDC', 'leadership Congo', 'académie politique', 'formation gratuite RDC', 'jeunesse congolaise'],
    date: '2026-08-03',
    author: 'Le Congo D\'Abord',
    category: 'Formation',
    readMinutes: 4,
    related: ['selection-candidats-merite', 'transparence-cotisations'],
    content: [
      "Un parti qui n'investit pas dans la formation de ses membres achète ses cadres ailleurs — avec tout ce que cela implique. {L'Académie Politique|/training} du Congo D'Abord fait le pari inverse : former gratuitement chaque membre qui veut apprendre.",
      "Le curriculum couvre 14 modules : leadership et prise de décision, gouvernance locale, finances publiques, communication politique, éthique et intégrité, droit électoral congolais, gestion de projets, mobilisation communautaire, et plus encore.",
      "La formation n'est pas décorative : elle compte pour 10% du {score de sélection des candidats|/candidates}. Un membre formé progresse dans le parti. Un membre non formé reste à la base. C'est la méritocratie appliquée, module après module.",
      "L'IA personnalise chaque parcours : selon votre profil et vos ambitions, {l'Agent Académie|/training} recommande les modules prioritaires, l'ordre optimal et le temps nécessaire — avec l'impact estimé sur votre score.",
      "L'éducation politique est la meilleure arme contre la manipulation. {Inscrivez-vous|/register}, formez-vous, et prenez votre place dans la transformation du Congo.",
    ],
  },
  {
    slug: '23-agents-ia-parti-congo',
    title: "Les 23 agents IA du Congo D'Abord : chaque tâche du parti, automatisée",
    description: "Inscription, sélection des candidats, formation, éthique, projets nationaux : découvrez les 23 agents d'intelligence artificielle qui font tourner Le Congo D'Abord 24h/24.",
    keywords: ['agents IA parti', 'intelligence artificielle politique RDC', 'automatisation parti', "Congo D'Abord", 'IA Afrique'],
    date: '2026-08-04',
    author: "Le Congo D'Abord",
    category: 'Technologie',
    readMinutes: 6,
    related: ['parti-politique-ia-rdc', 'selection-candidats-merite', 'snto-promesses-projets'],
    content: [
      "Un parti politique moderne, c'est des milliers de décisions par jour. Au {Congo D'Abord|/}, 23 agents d'intelligence artificielle spécialisés portent cette charge — pour que les humains se concentrent sur ce qui compte : décider et servir.",
      "Douze agents gèrent le parti au quotidien : validation des {inscriptions|/register}, cartographie des membres, {analyse des CV et scoring|/candidates}, {génération de politiques publiques|/policy}, priorisation des {besoins d'infrastructure|/infrastructure}, suivi des {cotisations|/contributions}, parcours de {formation personnalisés|/training}, gestion des cas d'{éthique|/ethics} et bien plus.",
      "Onze autres agents forment le {Système National de Transformation (SNTO)|/projects} : ils convertissent le manifeste en projets nationaux chiffrés, trouvent les financements, affectent les talents et suivent la livraison jusqu'au {tableau de bord exécutif|/projects/command-centre}.",
      "Le principe ne change jamais : l'IA propose, l'humain décide. Aucun agent ne prend de décision finale. L'intelligence artificielle élimine la lenteur et le favoritisme ; les organes du parti gardent le pouvoir.",
      "Et pour vous aider à mobiliser, un {moteur de croissance IA|/growth} génère posts, publicités et campagnes en 5 langues. La technologie la plus avancée d'Afrique, au service d'un seul objectif : un Congo dirigé par la compétence.",
      "Découvrez ces agents en action : {créez votre compte|/register} et posez vos questions directement aux agents du parti.",
    ],
  },
  {
    slug: 'du-village-a-la-presidence-structure',
    title: 'Du village à la Présidence : la structure à 7 niveaux qui compte chaque Congolais',
    description: "Comment Le Congo D'Abord organise 26 provinces, 145 territoires et des milliers de villages en une seule structure où chaque membre a sa place et sa voix.",
    keywords: ['structure parti RDC', 'organisation politique Congo', '26 provinces', 'village Congo', 'décentralisation RDC'],
    date: '2026-08-04',
    author: "Le Congo D'Abord",
    category: 'Structure',
    readMinutes: 5,
    related: ['parti-politique-ia-rdc', 'infrastructure-participative', 'diaspora-congolaise-engagement'],
    content: [
      "Dans la plupart des partis congolais, le village ne compte pas. Au {Congo D'Abord|/}, il est le socle. Notre structure à 7 niveaux relie chaque citoyen, du village jusqu'à la Présidence.",
      "National → Provincial (26 provinces) → Territoire/Ville (145 territoires, 33 villes) → Commune/Secteur/Chefferie → Quartier/Groupement → Cellule/Village → Diaspora. Chaque membre {inscrit|/register} est géolocalisé précisément dans cette hiérarchie.",
      "Pourquoi c'est révolutionnaire ? Parce que le parti sait, en temps réel, combien de membres il a dans chaque village — et cette information remonte jusqu'au {tableau de bord national|/dashboard}. Aucun autre parti congolais ne peut le dire.",
      "Cette structure alimente tout le reste : la {sélection des candidats au mérite|/candidates} tient compte de la crédibilité locale, et les {besoins d'infrastructure|/infrastructure} signalés au niveau du village deviennent des projets nationaux via le {SNTO|/projects}.",
      "Votre village mérite d'être sur la carte. {Rejoignez le mouvement|/register} et prenez votre place dans la structure.",
    ],
  },
  {
    slug: 'cinq-langues-nationales-plateforme',
    title: 'Français, Lingala, Kikongo, Tshiluba, Kiswahili : un parti qui parle votre langue',
    description: "Le Congo D'Abord est la première plateforme politique congolaise entièrement disponible dans les 5 langues nationales. L'inclusion linguistique n'est pas un slogan, c'est du code.",
    keywords: ['langues nationales RDC', 'Lingala politique', 'Kiswahili Congo', 'plateforme multilingue', 'inclusion RDC'],
    date: '2026-08-05',
    author: "Le Congo D'Abord",
    category: 'Inclusion',
    readMinutes: 4,
    related: ['du-village-a-la-presidence-structure', 'parti-politique-ia-rdc'],
    content: [
      "Un cultivateur du Kasaï et un commerçant de Goma ne parlent pas toujours la même langue. Au {Congo D'Abord|/}, ils utilisent pourtant la même plateforme — chacun dans la sienne.",
      "Français, Lingala, Kikongo, Tshiluba et Kiswahili : les 5 langues nationales de la RDC sont toutes disponibles, de l'{inscription|/register} jusqu'au {tableau de bord|/dashboard}. Vous choisissez, l'interface suit.",
      "Même l'{Agent Communication|/growth} du parti génère les messages dans les 5 langues, avec le registre culturel adapté à chacune. Un discours pensé à Kinshasa peut toucher un village de l'Équateur dans sa langue maternelle.",
      "L'inclusion linguistique compte aussi dans la {sélection des candidats|/candidates} : la maîtrise des langues fait partie des 8 critères de scoring. Parler à son peuple, c'est une compétence politique.",
      "Dans votre langue, votre voix porte plus loin. {Inscrivez-vous|/register} et choisissez la langue qui est la vôtre.",
    ],
  },
  {
    slug: 'diaspora-congolaise-engagement',
    title: 'Diaspora congolaise : agissez pour le pays sans quitter votre ville d\'accueil',
    description: "De Bruxelles à Montréal, la diaspora congolaise est pleinement intégrée au Congo D'Abord : vote à distance, cotisation en ligne, postes du parti. Voici comment participer.",
    keywords: ['diaspora congolaise', 'Congolais étranger', 'diaspora RDC politique', 'vote diaspora', 'engagement diaspora'],
    date: '2026-08-05',
    author: "Le Congo D'Abord",
    category: 'Diaspora',
    readMinutes: 5,
    related: ['du-village-a-la-presidence-structure', 'transparence-cotisations'],
    content: [
      "Des millions de Congolais vivent à l'étranger — et beaucoup veulent agir pour le pays sans savoir comment. Le {Congo D'Abord|/} fait de la diaspora le 7e niveau de sa structure, à part entière.",
      "Où que vous soyez — Afrique, Europe, Amériques, Asie, Océanie — vous vous {inscrivez en ligne|/register}, vous {cotisez par mobile money ou carte|/contributions} (12 USD/an), et vous devenez éligible aux postes diaspora du parti.",
      "La diaspora a un pouvoir de cotisation supérieur et un réseau international précieux. Votre engagement compte autant que celui d'un membre à Kinshasa — la {sélection des candidats|/candidates} applique les mêmes critères à tous.",
      "Vous pouvez aussi mobiliser votre communauté avec les {outils de croissance IA|/growth} et {inviter vos proches|/invite} restés au pays ou installés ailleurs.",
      "Loin du pays, proche du changement. {Rejoignez le mouvement depuis l'étranger|/register}.",
    ],
  },
  {
    slug: 'ethique-discipline-integrite-parti',
    title: "Éthique et intégrité : comment l'IA protège le parti contre la corruption",
    description: "L'Agent Éthique du Congo D'Abord analyse chaque cas d'intégrité avec des précédents comparables et recommande des sanctions proportionnelles. La corruption n'a pas sa place.",
    keywords: ['éthique politique RDC', 'anti-corruption Congo', 'intégrité parti', 'discipline politique', 'gouvernance RDC'],
    date: '2026-08-06',
    author: "Le Congo D'Abord",
    category: 'Intégrité',
    readMinutes: 5,
    related: ['selection-candidats-merite', 'transparence-cotisations'],
    content: [
      "La corruption a détruit la confiance des Congolais envers la politique. Le {Congo D'Abord|/} riposte avec une arme inhabituelle : un {agent IA dédié à l'éthique et à la discipline|/ethics}.",
      "Chaque cas signalé est analysé objectivement : type de violation, gravité, précédents dans d'autres partis africains, sanctions proportionnelles recommandées. Pas de règlements de comptes, pas d'impunité — une justice interne cohérente.",
      "Le score d'intégrité pèse pour 10% dans la {sélection des candidats|/candidates}. Un membre dont l'intégrité est entachée voit son éligibilité chuter. La probité n'est pas optionnelle, elle est mesurée.",
      "Combinée à la {transparence financière totale|/contributions} — où chaque dollar est traçable — cette approche rend la corruption structurellement difficile. On ne peut pas cacher ce qui est enregistré.",
      "Un parti propre, c'est un parti qui se surveille. {Rejoignez un mouvement qui refuse la corruption|/register}.",
    ],
  },
  {
    slug: 'moteur-croissance-ia-mobilisation',
    title: "Le moteur de croissance IA : 10 outils pour mobiliser en un clic",
    description: "Posts sociaux, publicités, campagnes email, scripts vidéo, hashtags, analytique : le Growth Engine du Congo D'Abord met le marketing politique professionnel entre toutes les mains.",
    keywords: ['marketing politique RDC', 'mobilisation numérique', 'outils IA campagne', 'réseaux sociaux Congo', 'growth engine'],
    date: '2026-08-06',
    author: "Le Congo D'Abord",
    category: 'Mobilisation',
    readMinutes: 5,
    related: ['23-agents-ia-parti-congo', 'diaspora-congolaise-engagement'],
    content: [
      "Mobiliser demande du temps, du talent et de l'argent — trois choses rares. Le {moteur de croissance IA|/growth} du Congo D'Abord les remplace par un clic.",
      "Dix outils intégrés : générateur de posts sociaux (5 langues), créateur de publicités, campagnes email, pages de destination, hashtags optimisés, scripts vidéo, plus l'analyse de performance, l'optimisation d'audience et les meilleurs horaires de publication pour la RDC.",
      "Un coordinateur local peut créer en 30 secondes une campagne qui aurait coûté des centaines de dollars à une agence. C'est la démocratisation de la communication politique — chaque membre devient un ambassadeur efficace.",
      "Ces outils s'articulent avec le {système de parrainage|/invite} : créez le message, partagez-le sur WhatsApp, suivez les inscriptions. La croissance devient mesurable et virale.",
      "Prêt à faire grandir le mouvement ? {Inscrivez-vous|/register} et accédez au moteur de croissance.",
    ],
  },
  {
    slug: 'centre-commandement-national-pilotage',
    title: "Le Centre de Commandement National : gouverner sur des chiffres, pas des impressions",
    description: "Projets livrés, budgets engagés, emplois créés, classement des provinces et des ministres, score de préparation électorale : le tableau de bord exécutif du Congo D'Abord.",
    keywords: ['tableau de bord politique', 'pilotage national RDC', 'gouvernance données', 'performance ministres', 'transparence gouvernement'],
    date: '2026-08-07',
    author: "Le Congo D'Abord",
    category: 'Gouvernance',
    readMinutes: 5,
    related: ['snto-promesses-projets', '23-agents-ia-parti-congo'],
    content: [
      "Quand nous gouvernerons, chaque citoyen pourra vérifier chaque promesse. Le {Centre de Commandement National|/projects/command-centre} rend cela possible : tout le pays sur un écran.",
      "En temps réel : projets livrés vs. en retard, budgets engagés et dépensés, emplois créés, citoyens bénéficiaires, classement de performance des provinces et des ministres, et un score global de préparation électorale.",
      "Ces données viennent directement du {SNTO|/projects}, qui suit chaque projet de la promesse à la livraison. Un ministre qui n'exécute pas se voit dans le classement. La performance devient publique, donc responsable.",
      "Les {tableaux de bord provinciaux et locaux|/dashboard} déclinent cette même transparence à chaque niveau de la {structure du parti|/du-village-a-la-presidence-structure}.",
      "La transparence n'est pas une promesse — c'est une architecture. {Rejoignez un parti qui se mesure|/register}.",
    ],
  },
  {
    slug: 'feuille-de-route-10-ans-mandats',
    title: "Une feuille de route sur 10 ans : ce que deux mandats peuvent transformer",
    description: "Fondations d'abord (routes, énergie, écoles, santé), industrialisation ensuite (rail, IA nationale, villes intelligentes). Comment le Congo D'Abord planifie 10 ans de transformation.",
    keywords: ['développement RDC 10 ans', 'plan national Congo', 'industrialisation RDC', 'vision long terme', 'transformation nationale'],
    date: '2026-08-07',
    author: "Le Congo D'Abord",
    category: 'Vision',
    readMinutes: 6,
    related: ['snto-promesses-projets', 'centre-commandement-national-pilotage'],
    content: [
      "On ne transforme pas un pays en un mandat. Le {Congo D'Abord|/} planifie sur 10 ans, avec un {agent IA dédié à la planification des deux mandats|/projects/second-term}.",
      "Premier mandat (années 1-5) — les fondations : réhabilitation des routes, programme énergie solaire, rénovation des écoles, hôpitaux régionaux, gouvernement numérique. L'infrastructure de base qui rend tout le reste possible.",
      "Second mandat (années 6-10) — la transformation : train rapide Kinshasa-Lubumbashi, infrastructure IA nationale, zones de traitement pour l'exportation minière, villes intelligentes. L'industrialisation qui fait décoller l'économie.",
      "L'IA alloue chaque projet au bon mandat selon la faisabilité, le financement disponible et la capacité d'exécution. Le tout est suivi dans le {Centre de Commandement|/projects/command-centre} et alimenté par le {think tank permanent du parti|/projects}.",
      "Une vision qui dépasse les slogans. {Rejoignez la transformation à long terme|/register}.",
    ],
  },
  {
    slug: 'securite-donnees-membres-chiffrement',
    title: "Vos données protégées : chiffrement bancaire pour chaque membre",
    description: "Le Congo D'Abord protège les données d'affiliation politique avec un chiffrement AES-256 de niveau bancaire et un accès réservé aux humains. En RDC, c'est un devoir, pas un luxe.",
    keywords: ['sécurité données RDC', 'protection vie privée', 'chiffrement politique', 'données membres', 'cybersécurité Congo'],
    date: '2026-08-08',
    author: "Le Congo D'Abord",
    category: 'Sécurité',
    readMinutes: 5,
    related: ['ethique-discipline-integrite-parti', 'parti-politique-ia-rdc'],
    content: [
      "En politique congolaise, une liste de membres entre de mauvaises mains peut ruiner des vies. Le {Congo D'Abord|/} traite la sécurité des données comme une question de survie, pas de conformité.",
      "Les informations sensibles (numéro d'identité, téléphone, adresse) sont chiffrées dans votre navigateur, avant même de quitter votre appareil, avec le standard AES-256-GCM — le même que les banques internationales.",
      "L'agent de cybersécurité {Sentinel|/security} veille en permanence : il bloque les robots, les tentatives d'injection et les accès automatisés. Seuls les humains accèdent à la plateforme, et chaque {inscription|/register} est protégée.",
      "Cette sécurité renforce la {transparence|/contributions} sans la contredire : les chiffres agrégés sont publics, mais l'identité de chaque membre reste protégée. Transparence des flux, confidentialité des personnes.",
      "Votre engagement politique vous appartient. {Rejoignez une plateforme qui protège ses membres|/register}.",
    ],
  },
  {
    slug: 'un-dollar-pouvoir-mobile-money',
    title: "1 USD par mobile money : la barrière d'entrée la plus basse de la politique congolaise",
    description: "M-Pesa, Orange Money, Airtel Money : comment le Congo D'Abord rend l'engagement politique accessible à chaque Congolais pour le prix d'un dollar par mois.",
    keywords: ['mobile money RDC', 'M-Pesa politique', 'cotisation 1 dollar', 'engagement accessible', 'Orange Money Congo'],
    date: '2026-08-08',
    author: "Le Congo D'Abord",
    category: 'Accessibilité',
    readMinutes: 4,
    related: ['transparence-cotisations', 'diaspora-congolaise-engagement'],
    content: [
      "La politique congolaise a longtemps été réservée à ceux qui ont de l'argent. Le {Congo D'Abord|/} brise cette barrière : un dollar par mois, payable par mobile money.",
      "M-Pesa, Orange Money, Airtel Money — les moyens que chaque Congolais utilise déjà. Pas besoin de compte bancaire, pas de déplacement. Vous {cotisez depuis votre téléphone|/contributions} en quelques secondes.",
      "Ce dollar n'est pas qu'un paiement : c'est la clé de votre {éligibilité|/candidates}. Cotisation à jour = accès aux nominations, aux candidatures, aux postes de direction. La méritocratie devient accessible à tous.",
      "Pour ceux qui préfèrent, la formule annuelle à 12 USD réduit les frais et garantit un statut actif toute l'année. La diaspora, elle, peut {cotiser en ligne depuis l'étranger|/diaspora-congolaise-engagement}.",
      "Un dollar pour reprendre votre pays en main. {Inscrivez-vous et cotisez|/register}.",
    ],
  },
  {
    slug: 'comment-devenir-candidat-rdc',
    title: "Comment devenir candidat aux élections en RDC : le guide complet 2027",
    description: "Vous voulez vous présenter aux élections en République Démocratique du Congo ? Voici les étapes concrètes, les critères de sélection et comment le Congo D'Abord choisit ses candidats au mérite.",
    keywords: ['comment devenir candidat RDC', 'se présenter élections Congo', 'candidature politique RDC', 'devenir député Congo', 'élections 2028 RDC'],
    date: '2026-08-09',
    author: "Le Congo D'Abord",
    category: 'Guide',
    readMinutes: 6,
    related: ['selection-candidats-merite', 'academie-politique-formation', 'un-dollar-pouvoir-mobile-money'],
    content: [
      "Vous rêvez de servir votre pays comme élu ? En RDC, la question n'est plus seulement « qui connaissez-vous » mais « que valez-vous ». Au {Congo D'Abord|/}, devenir candidat suit un chemin clair et méritocratique.",
      "Étape 1 : {inscrivez-vous comme membre|/register} et complétez votre profil (éducation, expérience, langues, ancrage local). Étape 2 : {mettez votre cotisation à jour|/contributions} — 1 USD/mois — car sans cotisation, aucune éligibilité.",
      "Étape 3 : renforcez votre score via l'{Académie Politique|/training}. La formation compte pour 10% de votre note de {sélection|/candidates}, aux côtés de l'éducation, de l'expérience, du leadership et de l'intégrité.",
      "Étape 4 : pour chaque poste, l'IA propose les 3 meilleurs profils aux organes du parti, qui décident. Votre score détaillé et vos justifications sont transparents — vous savez exactement où vous en êtes et comment progresser.",
      "Contrairement au système traditionnel, personne n'achète sa candidature ici. Vous la méritez, critère après critère. Découvrez la {formule de scoring complète|/selection-candidats-merite}.",
      "Votre parcours de candidat commence aujourd'hui. {Créez votre profil|/register} et visez le poste qui vous ressemble.",
    ],
  },
  {
    slug: 'parti-politique-kinshasa-rejoindre',
    title: "Rejoindre un parti politique à Kinshasa : pourquoi Le Congo D'Abord change la donne",
    description: "À Kinshasa, des millions de citoyens veulent s'engager autrement. Découvrez comment rejoindre Le Congo D'Abord dans la capitale : inscription, cellule locale, formation et candidatures.",
    keywords: ['parti politique Kinshasa', 'rejoindre parti Kinshasa', 'engagement politique Kinshasa', 'jeunesse Kinshasa politique', 'Kinshasa 2027'],
    date: '2026-08-09',
    author: "Le Congo D'Abord",
    category: 'Provinces',
    readMinutes: 4,
    related: ['du-village-a-la-presidence-structure', 'comment-devenir-candidat-rdc'],
    content: [
      "Kinshasa, plus de 15 millions d'habitants, cœur politique de la RDC. C'est aussi là que la lassitude envers la vieille politique est la plus forte. Le {Congo D'Abord|/} propose autre chose.",
      "En tant que Kinois, vous vous {inscrivez en quelques minutes|/register}, vous êtes rattaché à votre commune et votre quartier dans la {structure du parti|/du-village-a-la-presidence-structure}, et vous rejoignez une cellule locale active.",
      "La capitale concentre les talents : diplômés, entrepreneurs, leaders communautaires. La {sélection au mérite|/candidates} leur donne enfin un chemin vers les responsabilités, sans piston ni argent.",
      "Vous pouvez suivre l'{Académie Politique|/training}, signaler les {problèmes d'infrastructure|/infrastructure} de votre quartier, et {mobiliser votre réseau|/invite} — Kinshasa est le meilleur endroit pour faire grandir le mouvement.",
      "La transformation du Congo commence par sa capitale. {Rejoignez Le Congo D'Abord à Kinshasa|/register}.",
    ],
  },
  {
    slug: 'engagement-politique-lubumbashi-katanga',
    title: "Lubumbashi et le Katanga : l'engagement politique nouvelle génération",
    description: "Haut-Katanga, capitale minière du Congo. Découvrez comment les habitants de Lubumbashi rejoignent Le Congo D'Abord et transforment la richesse minière en développement local.",
    keywords: ['parti politique Lubumbashi', 'Haut-Katanga politique', 'engagement Katanga', 'mines Congo développement', 'Lubumbashi 2027'],
    date: '2026-08-10',
    author: "Le Congo D'Abord",
    category: 'Provinces',
    readMinutes: 4,
    related: ['parti-politique-kinshasa-rejoindre', 'feuille-de-route-10-ans-mandats'],
    content: [
      "Le Katanga produit une part immense de la richesse minière mondiale — mais ses habitants en voient trop peu les bénéfices. Le {Congo D'Abord|/} veut inverser cela, en commençant par l'engagement citoyen.",
      "À Lubumbashi et dans tout le Haut-Katanga, vous {rejoignez le parti en ligne|/register} et intégrez la {structure locale|/du-village-a-la-presidence-structure}. Vos préoccupations remontent jusqu'au {tableau de bord national|/dashboard}.",
      "Le {SNTO|/projects} planifie précisément ce type de transformation : zones industrielles, traitement local des minerais, corridors d'exportation — des projets chiffrés et suivis, pas des promesses.",
      "La {sélection au mérite|/candidates} valorise l'expertise minière et industrielle de la région. Ingénieurs, cadres, leaders communautaires du Katanga : votre compétence a enfin un débouché politique.",
      "Faites du Katanga un modèle de transformation. {Rejoignez Le Congo D'Abord à Lubumbashi|/register}.",
    ],
  },
  {
    slug: 'goma-nord-kivu-paix-developpement',
    title: "Goma et le Nord-Kivu : la politique au service de la paix et du développement",
    description: "Dans une région marquée par les conflits, Le Congo D'Abord propose un engagement politique tourné vers la paix, la reconstruction et le développement local. Voici comment participer depuis Goma.",
    keywords: ['parti politique Goma', 'Nord-Kivu politique', 'paix Est Congo', 'développement Kivu', 'reconstruction RDC'],
    date: '2026-08-10',
    author: "Le Congo D'Abord",
    category: 'Provinces',
    readMinutes: 5,
    related: ['engagement-politique-lubumbashi-katanga', 'infrastructure-participative'],
    content: [
      "L'Est de la RDC a trop souffert. À Goma et dans le Nord-Kivu, l'engagement politique doit servir la paix et la reconstruction. Le {Congo D'Abord|/} en fait une priorité structurelle.",
      "Malgré les défis, vous pouvez {rejoindre le parti en ligne|/register} et faire entendre la voix du Kivu dans la {structure nationale|/du-village-a-la-presidence-structure} — chaque village compte, même dans les zones les plus difficiles.",
      "L'{Agent Infrastructure|/infrastructure} recense les besoins urgents de reconstruction (routes, écoles, eau, santé) et les transforme en projets prioritaires via le {SNTO|/projects}.",
      "La {sélection des candidats|/candidates} valorise la crédibilité locale et l'intégrité — exactement ce dont l'Est a besoin pour reconstruire la confiance envers ses dirigeants.",
      "Construisons la paix par la compétence et la transparence. {Rejoignez Le Congo D'Abord à Goma|/register}.",
    ],
  },
  {
    slug: 'jeunes-diplomes-sans-emploi-politique',
    title: "Jeune diplômé sans emploi en RDC ? Votre compétence a une valeur politique",
    description: "Des milliers de jeunes Congolais diplômés cherchent leur place. Le Congo D'Abord transforme votre formation en atout politique concret, avec un chemin clair vers les responsabilités.",
    keywords: ['jeunes diplômés RDC', 'chômage jeunes Congo', 'emploi jeunesse RDC', 'opportunité jeunes Congo', 'leadership jeune Afrique'],
    date: '2026-08-11',
    author: "Le Congo D'Abord",
    category: 'Jeunesse',
    readMinutes: 5,
    related: ['comment-devenir-candidat-rdc', 'academie-politique-formation'],
    content: [
      "Vous avez un diplôme mais pas d'emploi, et la politique semble fermée à ceux qui n'ont ni argent ni relations ? Le {Congo D'Abord|/} a été construit précisément pour vous.",
      "Ici, votre {éducation et vos compétences|/candidates} valent des points réels dans la sélection — l'éducation compte pour 15%, l'expérience pour 20%. Votre parcours n'est plus invisible, il est mesuré et valorisé.",
      "L'{Académie Politique|/training} vous forme gratuitement au leadership, à la gouvernance et aux finances publiques — 14 modules qui augmentent votre score et vos chances d'accéder aux responsabilités.",
      "Pour 1 USD par mois, vous {devenez éligible|/contributions} aux postes et candidatures. La barrière financière la plus basse de la politique congolaise, pensée pour la jeunesse.",
      "Votre diplôme n'est pas un papier inutile — c'est un capital politique. {Inscrivez-vous et faites-le valoir|/register}.",
    ],
  },
  {
    slug: 'femmes-leadership-politique-congo',
    title: "Femmes congolaises et leadership politique : briser le plafond par le mérite",
    description: "En RDC, les femmes restent sous-représentées en politique. Le Congo D'Abord applique une sélection au mérite qui ne connaît pas le genre — voici comment les femmes prennent leur place.",
    keywords: ['femmes politique RDC', 'leadership féminin Congo', 'parité RDC', 'femmes candidates Congo', 'égalité genre Afrique'],
    date: '2026-08-11',
    author: "Le Congo D'Abord",
    category: 'Inclusion',
    readMinutes: 5,
    related: ['jeunes-diplomes-sans-emploi-politique', 'selection-candidats-merite'],
    content: [
      "Les femmes congolaises portent une grande part de l'économie et de la société — mais restent trop rares aux postes de décision. Le {Congo D'Abord|/} change les règles du jeu.",
      "Notre {formule de sélection|/candidates} est aveugle au genre : elle mesure l'éducation, l'expérience, le leadership, la crédibilité locale et l'intégrité. Une femme compétente obtient le même score qu'un homme aux mêmes qualités — et le poste va au meilleur.",
      "L'{Académie Politique|/training} offre aux femmes les mêmes outils de progression, gratuitement. Et la {structure du parti|/du-village-a-la-presidence-structure} leur ouvre des rôles à chaque niveau, du village au national.",
      "Pour 1 USD par mois, chaque Congolaise devient {éligible|/contributions} aux candidatures. C'est l'accessibilité qui rend l'égalité réelle, pas seulement proclamée.",
      "Le Congo a besoin de toutes ses filles autant que de tous ses fils. {Rejoignez le mouvement|/register} et prenez la place que vous méritez.",
    ],
  },
  {
    slug: 'transparence-financement-partis-rdc',
    title: "Où va l'argent des partis politiques en RDC ? La réponse du Congo D'Abord",
    description: "Le financement opaque des partis nourrit la corruption en RDC. Découvrez comment Le Congo D'Abord rend chaque dollar traçable et redonne le pouvoir aux membres cotisants.",
    keywords: ['financement partis RDC', 'argent politique Congo', 'transparence financière parti', 'corruption financement', 'où va argent parti'],
    date: '2026-08-12',
    author: "Le Congo D'Abord",
    category: 'Transparence',
    readMinutes: 5,
    related: ['transparence-cotisations', 'ethique-discipline-integrite-parti'],
    content: [
      "Qui finance les partis congolais ? Trop souvent, personne ne le sait — et c'est justement le problème. L'argent occulte achète l'influence et corrompt les décisions. Le {Congo D'Abord|/} fait le choix inverse : la transparence totale.",
      "Le parti est financé par ses membres, 1 USD à la fois, via {mobile money traçable|/un-dollar-pouvoir-mobile-money}. Chaque paiement est enregistré, chaque statut est visible. Il n'y a pas de financier caché parce qu'il n'y a pas besoin de financier caché.",
      "Cette transparence des {cotisations|/contributions} se combine avec l'{Agent Éthique|/ethics} qui traque les manquements à l'intégrité. On ne peut ni cacher l'argent, ni cacher les fautes.",
      "Résultat : un parti qui appartient réellement à ses membres, pas à des bailleurs de l'ombre. Avec suffisamment de cotisants, le parti est totalement indépendant — l'indépendance par la base.",
      "Reprenez le contrôle du financement politique. {Rejoignez un parti 100% transparent|/register}.",
    ],
  },
  {
    slug: 'application-politique-telephone-rdc',
    title: "Faire de la politique depuis son téléphone en RDC : c'est désormais possible",
    description: "Inscription, cotisation, formation, mobilisation : tout Le Congo D'Abord tient dans votre téléphone. Découvrez la première plateforme politique 100% mobile de la RDC.",
    keywords: ['application politique RDC', 'politique smartphone Congo', 'plateforme mobile parti', 'engagement mobile RDC', 'politique en ligne Congo'],
    date: '2026-08-12',
    author: "Le Congo D'Abord",
    category: 'Technologie',
    readMinutes: 4,
    related: ['un-dollar-pouvoir-mobile-money', 'moteur-croissance-ia-mobilisation'],
    content: [
      "En RDC, le téléphone est le premier — souvent le seul — accès à internet. Le {Congo D'Abord|/} est pensé pour cela : tout se fait depuis votre mobile, sans ordinateur ni bureau.",
      "Vous {vous inscrivez|/register} en quelques minutes, vous {cotisez par mobile money|/contributions}, vous suivez l'{Académie Politique|/training} entre deux trajets, et vous {mobilisez sur WhatsApp|/invite} — tout dans votre poche.",
      "La plateforme est légère et rapide, optimisée pour les connexions 3G et le coût des données mobiles congolaises. Pas besoin d'un smartphone dernier cri pour participer à la transformation du pays.",
      "Même les {23 agents IA|/23-agents-ia-parti-congo} et le {moteur de croissance|/growth} sont accessibles depuis votre écran. La technologie la plus avancée d'Afrique, dans la main de chaque Congolais.",
      "La politique de votre pays, à portée de pouce. {Téléchargez votre avenir — inscrivez-vous|/register}.",
    ],
  },
  {
    slug: 'coordinateur-local-parti-role',
    title: "Devenir coordinateur local du parti : le rôle qui transforme votre communauté",
    description: "Les coordinateurs locaux sont l'épine dorsale du Congo D'Abord. Découvrez ce rôle, ses responsabilités et comment il vous positionne comme leader de votre communauté.",
    keywords: ['coordinateur local parti', 'leader communautaire RDC', 'responsable cellule parti', 'organiser communauté Congo', 'militant RDC'],
    date: '2026-08-13',
    author: "Le Congo D'Abord",
    category: 'Guide',
    readMinutes: 5,
    related: ['du-village-a-la-presidence-structure', 'jeunes-diplomes-sans-emploi-politique'],
    content: [
      "Chaque grand mouvement repose sur des personnes de terrain. Au {Congo D'Abord|/}, ce sont les coordinateurs locaux — les leaders qui font vivre le parti dans chaque village, quartier et commune.",
      "Un coordinateur accueille les nouveaux {membres|/register}, anime sa cellule dans la {structure à 7 niveaux|/du-village-a-la-presidence-structure}, remonte les {besoins d'infrastructure|/infrastructure} de sa communauté et organise la mobilisation locale.",
      "C'est aussi un tremplin : la crédibilité locale et le leadership comptent lourd dans la {sélection des candidats|/candidates}. Un bon coordinateur se construit un chemin naturel vers les responsabilités électives.",
      "Le parti vous outille : {formation gratuite|/training}, {outils de croissance IA|/growth} pour mobiliser, et un {tableau de bord|/dashboard} pour suivre votre communauté. Vous n'êtes jamais seul.",
      "Devenez le visage du changement dans votre communauté. {Inscrivez-vous et proposez-vous comme coordinateur|/register}.",
    ],
  },
  {
    slug: 'pourquoi-nouveau-parti-congo-2027',
    title: "Pourquoi un nouveau parti politique en RDC en 2027 ? La réponse honnête",
    description: "Encore un parti ? Non — un système d'exploitation politique. Découvrez ce qui rend Le Congo D'Abord fondamentalement différent de tout ce qui existe en RDC.",
    keywords: ['nouveau parti RDC 2027', 'pourquoi Congo D\'Abord', 'parti différent Congo', 'alternative politique RDC', 'renouveau politique Congo'],
    date: '2026-08-13',
    author: "Le Congo D'Abord",
    category: 'Vision',
    readMinutes: 6,
    related: ['parti-politique-ia-rdc', 'transparence-financement-partis-rdc', 'comment-devenir-candidat-rdc'],
    content: [
      "« Encore un parti ? » C'est la question légitime de tout Congolais fatigué des promesses. La réponse du {Congo D'Abord|/} est simple : nous ne sommes pas un parti de plus, nous sommes un système.",
      "Les partis traditionnels vendent des candidatures ; nous les {attribuons au mérite|/candidates}. Ils cachent leurs finances ; nous {traçons chaque dollar|/transparence-financement-partis-rdc}. Ils oublient le village ; nous {cartographions chaque citoyen|/du-village-a-la-presidence-structure}. Ils promettent ; nous {suivons chaque projet jusqu'à la livraison|/projects}.",
      "Vingt-trois {agents d'intelligence artificielle|/23-agents-ia-parti-congo} font tourner ce système 24h/24, dans 5 langues, avec une sécurité de niveau bancaire. Rien de comparable n'existe en Afrique politique.",
      "Et tout cela pour 1 USD par mois — la barrière d'entrée la plus basse du continent. La compétence remplace l'argent ; la transparence remplace l'opacité ; les données remplacent les impressions.",
      "2027 n'est pas juste une élection de plus. C'est l'occasion de changer la manière même de faire de la politique au Congo. {Rejoignez la différence|/register}.",
    ],
  },
];

export function getPostBySlug(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find(p => p.slug === slug);
}
